(function(){
const firstVolume=window.startCase;
const V=[
null,
{era:'战国·秦',title:'南门新法',role:'秦县令',theme:'赏罚信用、什伍连坐与告奸',
 intro:['南门重赏已经兑现，新法随驿骑抵达县中。','逃兵之母藏子、韩甲借告奸报私仇，整里百姓面临连坐。'],
 evidence:[['南门赏券','赏金确已足额兑现'],['里伍名籍','两户案发时并不在里'],['韩甲告书','告发人与被告有争田旧怨']],
 conflict:['变法令史','新法贵在必行。若逐户查知情，威势何在？','里正','法若把不知情者也定罪，百姓只会先学会互害。'],
 crisis:[['依身份全里同坐','all','执行最快，责任完全取决于同里身份'],['分别审查知情、藏匿与诬告','bounded','调查较慢，但区分具体行为'],['取消告奸与连坐','loose','避免株连，也削弱新法互监结构']],
 court:[['赏罚信用来自什么？',[['政府先兑现公开承诺','trust'],['刑罚足够严厉','fear'],['官吏临时决定','secret']]],['怎样处理韩甲告发？',[['核实后追究故意诬告','verify'],['告发有利便不问真假','use'],['所有告发均不采纳','none']]],['怎样下县执行？',[['公开奖罚并限定连坐范围','rule'],['一里有罪全里同坐','all'],['不公布具体标准','secret']]]],
 notes:[['徙木立信','商鞅以兑现重赏建立新法信用。'],['赏罚必信','法令信用不仅来自惩罚，也来自政府履行承诺。'],['什伍连坐','编户互监扩大了国家控制，也扩大身份连带责任。'],['告奸机制','奖励告发能获得信息，也可能诱发诬告与私人报复。'],['变法与富国强兵','治理成效不能自动证明所有手段正当。'],['历史评价边界','不能把现代个人责任原则直接当作秦法规范。']],
 endings:{good:['信与刑之间','新法保持信用，藏匿、知情与诬告被分别处理。'],hard:['举里皆惧','全里同坐，告发骤增，邻里信任迅速崩解。'],weak:['法令失信','奖罚与适用标准反复变化，新法只剩恐惧。']}},
{era:'西汉·文帝',title:'缇萦叩阙',role:'廷尉府属官',theme:'废肉刑、替刑与制度纠错',
 intro:['淳于意将受肉刑，缇萦随囚车入长安上书。','她既求救父，也提出受刑者身体不可复续、无由改过。'],
 evidence:[['缇萦奏书','把孝行推进为肉刑存废问题'],['旧日行刑簿','记录肉刑后的长期伤残'],['河东伤亡奏报','高额笞刑造成死亡']],
 conflict:['廷尉正','旧刑沿用已久，足以示众。废之之后，何以禁奸？','缇萦','若受刑之后再无改过之路，刑罚究竟要人畏惧，还是要人归善？'],
 crisis:[['只赦淳于意','pardon','个案获救，普遍规则不变'],['废肉刑并细化替刑规则','reform','改革方向与执行尺度同时处理'],['维持旧有肉刑','old','避免替刑未知风险，保留不可逆伤残']],
 court:[['奏书核心是什么？',[['不可逆伤残阻断改过','purpose'],['只强调孝女感天','pardon'],['沿用已久即合理','old']]],['替刑怎样设计？',[['依罪责分等并限制笞数','graded'],['一律五百笞','harsh'],['只写务从宽仁','vague']]],['伤亡如何上报？',[['如实记录并继续修正','feedback'],['写成旧疾维护新制','hide'],['立刻恢复肉刑','old']]]],
 notes:[['缇萦上书','缇萦上书推动汉文帝刑制改革。'],['肉刑不可逆性','黥、劓、刖会造成永久身体伤残。'],['替代刑风险','刑名变轻不代表实际伤害必然降低。'],['罪责分等','替刑仍需保持刑罚轻重阶梯。'],['执行规范','刑具、部位、次数决定制度真实效果。'],['信息反馈','公开副作用是制度继续纠错的前提。']],
 endings:{good:['史官之笔','改革保留伤亡记录并继续调整，制度从后果中学习。'],hard:['笞下新伤','肉刑之名消失，高额笞刑却成为变相重刑。'],weak:['一人得赦','父女团聚，另一辆囚车仍驶向旧刑。']}},
{era:'唐·长安',title:'官帛匿盗案',role:'大理寺评事',theme:'《唐律疏议》、亲属容隐与行为边界',
 intro:['崔六涉嫌盗取官帛，逃入兄长崔安家。','崔安拒绝告发并提供不在场证明，灶后又发现官帛碎片。'],
 evidence:[['染坊账簿','击破整夜在家的口供'],['兄长初供','前后陈述互相矛盾'],['官帛碎片','可能支持积极藏匿赃物']],
 conflict:['库吏','兄弟同居，一人盗则一家同罪。','崔安','唐律许亲属相隐，难道我不告发弟弟也有罪？'],
 crisis:[['分别判断不告发、伪证与藏赃','separate','承认亲隐但审查行为边界'],['兄弟依身份同罪','same','以家族身份替代个别行为'],['亲属关系使一切协助免责','absolute','把容隐扩张为绝对免责']],
 court:[['先审什么？',[['亲属范围与具体行为','scope'],['同居身份即可定罪','same'],['套用现代拒证权','modern']]],['如何使用染坊账簿？',[['只击破不在场口供','limited'],['直接证明盗窃成立','over'],['完全排除书证','none']]],['怎样裁判崔安？',[['容隐、伪证、藏赃分别判断','separate'],['与崔六同罪','same'],['全部免责','absolute']]]],
 notes:[['《唐律疏议》','唐律以律文与疏议形成系统规范。'],['同居相为隐','一定范围亲属可相互容隐。'],['严重犯罪例外','谋叛以上等严重犯罪不适用通常容隐。'],['行为边界','不告发、通风报信、伪证与藏赃并非同一行为。'],['礼法结合','亲属伦理被纳入国家法律结构。'],['现代对照边界','唐律容隐不等同现代亲属拒证权。']],
 endings:{good:['礼法有界','亲属伦理被承认，却没有吞没具体行为责任。'],hard:['一门同罪','案件迅速结清，身份取代了行为审查。'],weak:['亲隐无边','容隐被扩大成任何亲属协助都不受约束。']}},
{era:'南宋·临安',title:'药圃洗冤',role:'提刑司属官',theme:'检验、口供与翻异别勘',
 intro:['赵员外死于雨夜药圃，赘婿陆惟恭刑讯后认罪又翻供。','县衙把无血短刃列为凶器，尸格却只记有颈部索沟。'],
 evidence:[['尸格与索沟','排除短刃作为直接致命工具'],['雨势簿','目击者所述时辰大雨遮目'],['刑讯记录','认罪发生在夹讯之后']],
 conflict:['原审知县','既有认罪口供，何必为几道伤痕重开案卷？','仵作','口供会迎合刑具，尸伤却不会看官长脸色。'],
 crisis:[['启动别勘并复验尸伤','review','让不同官署重新调查'],['维持原供定罪','confession','以认罪口供获得确定性'],['只凭目击者改判他人','witness','从一个单一证据跳到另一个']],
 court:[['先处理什么矛盾？',[['尸格与凶器不符','autopsy'],['认罪即可结案','confession'],['被告品行不佳','character']]],['翻供怎样处理？',[['查刑讯并启动别勘','review'],['翻供一律加罪','punish'],['翻供即无罪','free']]],['最终证据链如何形成？',[['检验、雨势、证言互证','chain'],['只采初供','confession'],['只采一名目击者','witness']]]],
 notes:[['《洗冤集录》','宋代检验知识强调尸伤与现场核验。'],['尸格制度','检验结果以规范文书进入案卷。'],['口供局限','刑讯可能使口供迎合预设案情。'],['翻异别勘','翻供案件可由不同官司另行审勘。'],['证据互证','检验、环境记录与证言应相互校验。'],['青天叙事边界','纠错依赖程序与证据，不只依赖清官直觉。']],
 endings:{good:['雨歇见痕','别勘重新排列尸格、雨势与证言，疑案获得纠正。'],hard:['供词成狱','初供压过全部外部矛盾，案卷获得了错误确定性。'],weak:['一言定罪','目击者取代口供成为新的单一证据。']}},
{era:'明·江南',title:'一纸婚书',role:'江南县丞',theme:'户婚秩序、父母主婚与文书真伪',
 intro:['沈素娘被族叔先后许配陆、赵两家，两家都持婚书到县衙。','陆家婚书有知县朱批，印文却可能伪造。'],
 evidence:[['两家聘财簿','族叔先后收受两家财物'],['县印样式簿','朱批印文与官印不符'],['素娘陈词','本人未参与订约且家产受控制']],
 conflict:['沈族叔','婚姻由家长作主，我所做皆为宗族。','沈素娘','两份婚书都写着我的名字，却没有一句是我说的话。'],
 crisis:[['分别处理主婚权、双聘与伪造','documents','在当时制度内拆分责任'],['直接套用现代婚姻自由','modern','价值清楚但跨越时代规范'],['维护宗族决定权','clan','个人处境被交给家族权力']],
 court:[['先核验什么？',[['婚书、聘财与主婚权限','documents'],['只问本人愿嫁谁','modern'],['聘财高者得婚','property']]],['伪造朱批如何处理？',[['核印并追查伪造者','verify'],['官文书一概可信','authority'],['旧约存在便无关紧要','ignore']]],['最终怎样处置？',[['拆分婚约、财物与伪造责任','separate'],['强制履行旧约','force'],['宗族自行决定','clan']]]],
 notes:[['明律户婚秩序','婚姻被置于家族、户籍与礼制秩序中。'],['父母主婚','家长权力是当时婚姻成立的重要结构。'],['婚书与聘财','文书和财物影响成约及悔婚责任。'],['一女两许','重复订婚会产生婚姻与财产纠纷。'],['伪造官文书','公文形式仍需核验，不能因官印外观绝对采信。'],['时代评价边界','不能把现代婚姻自由直接写成明代裁判规则。']],
 endings:{good:['婚书之外','伪造朱批与双重收聘被分别处理，素娘陈词进入正卷。'],hard:['宗祠定婚','家族重新掌握决定，伪造官批无人追究。'],weak:['越代判词','现代原则救下素娘，却没有回答明代制度争点。']}},
{era:'清·刑部',title:'秋审生死册',role:'秋审司官',theme:'死刑复核、缓决、可矜与留养',
 intro:['周成因械斗致死被判斩监候，原审报情实。','供词有刑讯记号，尸伤方向矛盾，证人又在秋审前翻供。'],
 evidence:[['刑讯供词','关键供述形成于夹讯之后'],['仵作格目','致命伤方向与所报凶器不合'],['证人翻供','原证人称受县役诱导']],
 conflict:['原审知县','案已定谳，再翻旧卷只会损害司法威信。','周母','他是独子，我求的不是无罪，是让事实查清以后再谈留养。'],
 crisis:[['先审事实疑点再定秋审分类','review','事实与恩情分开'],['依原审列情实','real','强调确定性与官僚秩序'],['直接因独子列留养','family','身份情节覆盖事实审查']],
 court:[['三证冲突如何处理？',[['提回重审并重新对质','review'],['只采认罪供词','real'],['有翻供即改可矜','mercy']]],['留养承祀何时审？',[['事实核清后依法审查','family'],['独子当然无罪','free'],['身份情节一概不看','none']]],['秋审怎样定类？',[['缓决并继续复核','delay'],['情实勾决','real'],['只写留养不述疑点','family']]]],
 notes:[['斩监候','死刑监候案件并非立即执行。'],['秋审复核','中央在秋季集中复核死刑案件。'],['情实与缓决','情实倾向执行，缓决则暂缓并继续审查。'],['可矜','情有可原与事实不清不是同一问题。'],['留养承祀','独子奉养老亲可能进入特殊审查。'],['慎刑与皇权','秋审兼具慎刑纠错与皇权最终裁决性质。']],
 endings:{good:['红册缓勾','案件列缓决，关键伤痕与翻供重新核验。'],hard:['情实勾决','原审被维持，刑讯记号与格目矛盾退出最终题本。'],weak:['留养之门','宗法孝养进入审查，却没有充分回答事实疑点。']}},
{era:'清末·修律馆',title:'新律之争',role:'修订法律馆参议',theme:'礼法之争、近代刑法与司法主权',
 intro:['新刑律草案试图区分犯罪与道德，建立近代刑罚体系。','礼教派要求保留伦理特别规范，列强又以司法落后拒绝撤废领事裁判权。'],
 evidence:[['新刑律草案','采用近代专门刑法典体例'],['礼教派签注','反对割裂礼教与法律'],['领事裁判照会','修律与司法主权目标相连']],
 conflict:['法理派参议','刑律应规定犯罪，不应把全部伦理义务都交给刑罚。','礼教派大臣','中国亲属名分若不入律，新法纵然整齐，又是谁的法律？'],
 crisis:[['逐条区分犯罪、伦理与过渡规范','balance','承认争议并建立边界'],['传统伦理全部原样入刑','ritual','文化连续优先'],['完全照搬外国法典','copy','技术移植最快，适应性最弱']],
 court:[['修律首先解决什么？',[['刑律边界与罪刑规则','modern'],['所有伦理原样入刑','ritual'],['只满足外国要求','foreign']]],['礼法争议怎样处理？',[['逐条说明并公开理由','balance'],['凡传统即保留','ritual'],['凡伦理即删除','modern']]],['主权目标怎样理解？',[['修律相关但不能直接换取撤废治外法权','sovereignty'],['照搬即可收回主权','copy'],['主权与司法改革无关','none']]]],
 notes:[['《大清新刑律》','清末编纂近代意义上的专门刑法典。'],['礼法之争','法理派与礼教派争论法律和伦理的边界。'],['罪刑法定方向','新律减少比附并重构犯罪与刑罚体系。'],['刑罚体系近代化','主刑、从刑等体例发生变化。'],['领事裁判权','修律与收回司法主权目标相联系。'],['移植与转化','采用外国法技术不等于制度自动落地。']],
 endings:{good:['新律未竟','草案在争论和妥协中成形，并改变后来的刑法道路。'],hard:['旧律新名','法典更名，礼教结构仍居核心。'],weak:['纸上主权','草案获得外国顾问称许，治外法权却未因此立即撤废。']}}
];
let C,S,Q=[],done=null;
function fresh(i){return{i,act:0,step:0,notes:[],evidence:[],choices:[],strategy:null,ending:null,savedAt:null}}
function key(i){return'av-five-'+i}
function save(){S.savedAt=Date.now();localStorage.setItem(key(S.i),JSON.stringify(S))}
function load(i){try{return JSON.parse(localStorage.getItem(key(i)))||fresh(i)}catch(e){return fresh(i)}}
function shell(){document.getElementById('imGame')?.remove();const e=document.createElement('section');e.id='imGame';e.className='v3 av';e.innerHTML=`<div class="v-bg avbg i${S.i}"></div><header class="v-top"><div><small id="vAct"></small><b>${C.title}</b></div><div><button onclick="avNotes()">法脉札记 <em id="vNoteCount"></em></button><button onclick="avExit()">返回八案</button></div></header><aside class="v-goal"><b>当前目标</b><span id="vGoal"></span><div class="v-progress">${[0,1,2,3,4].map(i=>`<i id="vP${i}"></i>`).join('')}</div></aside><div class="v-ye avchar i${S.i}"></div><main id="vStage"></main><div id="vDialog" class="v-dialog hidden" onclick="avAdvance()"><strong id="vSpeaker"></strong><p id="vText"></p><span id="vNext">点击继续 ▾</span><div id="vChoices"></div></div><div id="vModal" class="v-modal hidden"></div></section>`;document.body.appendChild(e)}
const actNames=['时代入局','案情发现','证据对质','制度抉择','最终裁断'];
function start(i){C=V[i];S=load(i);shell();if(S.savedAt&&(S.act||S.evidence.length||S.ending))modal(`<h1>继续第${'一二三四五'[S.act]}幕？</h1><p>已解锁 ${S.notes.length}/6 条法脉札记。</p><button class="primary" onclick="avRun()">继续存卷</button><button onclick="avRestart()">重新开始</button>`);else run()}
function run(){close();paint();if(S.ending)return ending();if(S.act===0)return intro();if(S.act===1)return investigate();if(S.act===2)return confront();if(S.act===3)return crisis();court()}
function paint(){document.getElementById('vAct').textContent=`第${'二三四五六七八'[S.i-1]}卷 · ${C.era} · ${actNames[S.act]}`;document.getElementById('vGoal').textContent=[`理解${C.theme}`,`依次核验三件关键材料`,`让证据进入人物对质`,`承担制度选择的人物后果`,`在正式裁断中运用本卷知识`][S.act];document.getElementById('vNoteCount').textContent=S.notes.length;[0,1,2,3,4].forEach(i=>document.getElementById('vP'+i).className=i<S.act?'done':i===S.act?'now':'')}
function intro(){stage(`<div class="v-center"><div class="v-seal">${'二三四五六七八'[S.i-1]}</div><h1>${C.title}</h1><p>${C.intro.join('<br>')}</p><button class="primary" onclick="avIntroTalk()">进入时代</button></div>`)}
function introTalk(){dialogue([['旁白',C.intro[0]],[C.role,C.intro[1]],[C.conflict[0],C.conflict[1]],[C.conflict[2],C.conflict[3]],[C.role,'你决定先以何种立场进入案件？',C.crisis.map(x=>[x[0],x[1],x[2]])]],()=>unlock([0,1],finish))}
function investigate(){stage(`<div class="v-three">${C.evidence.map((x,i)=>`<button ${i>S.evidence.length?'disabled':''} onclick="avEvidence(${i})"><b>${i+1} · ${x[0]}</b><span>${i<S.evidence.length?'已收入案卷':'点击核验'}</span></button>`).join('')}</div><div class="v-task">按顺序核验材料。每件证据只回答一个事实问题，不会自动证明全案。</div>`)}
function evidence(i){if(i>S.evidence.length)return;if(!S.evidence.includes(i))S.evidence.push(i);save();modal(`<small>证据收集</small><h2>${C.evidence[i][0]}</h2><p>${C.evidence[i][1]}</p><p><b>证据边界：</b>该材料需要与其他事实互证，不能单独替代完整裁断。</p><button class="primary" onclick="avContinueEvidence()">收入案卷</button>`)}
function continueEvidence(){close();if(S.evidence.length===3)unlock([2,3],finish);else run()}
function confront(){stage(`<div class="v-center"><h1>人物对质</h1><p>三件材料已经形成证据链。现在让两种制度立场直接交锋。</p><button class="primary" onclick="avConfrontTalk()">开始对质</button></div>`)}
function confrontTalk(){dialogue([[C.role,`“${C.evidence[0][0]}”说明${C.evidence[0][1]}；其余材料又补足了事实链。`],[C.conflict[0],C.conflict[1]],[C.conflict[2],C.conflict[3]],[C.role,'你不能只判断谁在说谎，还要决定当时制度如何处理这种冲突。']],finish)}
function crisis(){stage(`<div class="v-center"><h1>制度抉择</h1><p>调查已经结束。现在只处理人物和制度后果，不再增加新证据。</p><div class="v-decisions">${C.crisis.map(x=>`<button onclick="avStrategy('${x[1]}')">${x[0]}<small>${x[2]}</small></button>`).join('')}</div></div>`)}
function strategy(x){S.strategy=x;save();unlock([4],finish)}
function court(){stage(`<div class="v-court"><h1>${S.i===7?'修律馆表决':'正式裁断'}</h1><p>三轮回应将决定本卷结局。前四幕的证据和札记在此转化为可用理由。</p><button class="primary" onclick="avCourtTalk()">开始</button></div>`)}
function courtTalk(){const lines=[];C.court.forEach((q,n)=>{lines.push([n===2?'主审者':C.conflict[0],q[0]]);lines.push([C.role,'你的回应是——',q[1].map(x=>[x[0],x[1],x[0]])])});dialogue(lines,()=>unlock([5],resolve))}
function resolve(){const good=['bounded','reform','separate','review','documents','balance'];let id='weak';if(S.choices.some(x=>['all','same','confession','real','clan','ritual'].includes(x))||['all','same','old','clan','real','ritual'].includes(S.strategy))id='hard';if(S.choices.filter(x=>['trust','verify','rule','purpose','graded','feedback','scope','limited','separate','autopsy','review','chain','documents','verify','review','family','delay','modern','balance','sovereignty'].includes(x)).length>=2||good.includes(S.strategy))id='good';S.ending=id;save();ending()}
function ending(){const d=C.endings[S.ending]||C.endings.weak;stage(`<div class="v-end"><small>第${'二三四五六七八'[S.i-1]}卷结局</small><h1>${d[0]}</h1><p>${d[1]}</p><div class="v-graph"><b>本卷知识图谱</b>${S.notes.map(i=>`<span>${C.notes[i][0]}</span>`).join('')}<p>时代背景 → 人物冲突 → 证据调查 → 制度适用 → 历史后果</p></div><button class="primary" onclick="avNotes()">查看完整札记</button><button onclick="avComplete()">归档并返回八案</button></div>`)}
function finish(){modal(`<small>本幕完成</small><h1>${actNames[S.act]}</h1><p>${['你已经理解本卷时代矛盾。','事实材料已进入案卷。','人物立场已被证据检验。','你已承担制度选择的后果。','裁断完成。'][S.act]}</p><button class="primary" onclick="avNext()">进入下一幕</button>`)}
function next(){close();S.act++;save();run()}
function unlock(ids,cb){ids.forEach(i=>{if(!S.notes.includes(i))S.notes.push(i)});save();modal(`<small>法脉札记收集</small>${ids.map(i=>`<h2>${C.notes[i][0]}</h2><p>${C.notes[i][1]}</p>`).join('')}<button class="primary" id="avU">继续剧情</button>`);document.getElementById('avU').onclick=()=>{close();cb()}}
function notes(){modal(`<h1>${C.title} · 法脉札记</h1>${C.notes.map((n,i)=>`<article class="${S.notes.includes(i)?'':'locked'}"><h2>${S.notes.includes(i)?n[0]:'尚未解锁'}</h2><p>${S.notes.includes(i)?n[1]:'继续推进对应剧情。'}</p></article>`).join('')}<button onclick="avClose()">合卷</button>`)}
function dialogue(lines,cb){Q=lines.slice();done=cb;nextLine()}function nextLine(){if(!Q.length){hide();const f=done;done=null;if(f)f();return}const l=Q.shift(),d=document.getElementById('vDialog');d.classList.remove('hidden');document.getElementById('vSpeaker').textContent=l[0];document.getElementById('vText').textContent=l[1];const b=document.getElementById('vChoices');b.innerHTML='';document.getElementById('vNext').hidden=!!l[2];if(l[2])l[2].forEach((x,i)=>{const y=document.createElement('button');y.innerHTML=`<b>${String.fromCharCode(65+i)}</b>${x[0]}<small>${x[2]}</small>`;y.onclick=e=>{e.stopPropagation();S.choices.push(x[1]);save();nextLine()};b.appendChild(y)})}
function advance(){if(document.getElementById('vChoices').children.length)return;nextLine()}function hide(){document.getElementById('vDialog').classList.add('hidden')}function stage(h){document.getElementById('vStage').innerHTML=h}function modal(h){const m=document.getElementById('vModal');m.classList.remove('hidden');m.innerHTML=`<div>${h}</div>`}function close(){document.getElementById('vModal').classList.add('hidden')}
function complete(){window.unlockVolume&&window.unlockVolume(S.i,C.endings[S.ending][0],S.choices);exit()}
function exit(){save();document.getElementById('imGame')?.remove();window.openMap()}
/* replaced by the structured supplement table below
const EXTRA={1:{e:['县署施行牒','县令曾批示“连坐须核实知情与藏匿”，证明基层并非只能机械株连。'],q:[['如何理解什伍连坐的历史作用？',[['它强化编户互监与国家控制，同时扩大身份连带责任','history'],['它与现代个人责任完全相同','modern'],['它只有道德劝善作用','moral']]],['法令信用如何维持？',[['奖罚标准公开且政府也受承诺约束','promise'],['不断加重刑罚即可','terror'],['允许官吏随时改变标准','arbitrary']]]},2:{e:['诏令改制草案','草案把黥劓改为笞刑，却未细定次数与行刑规范。'],q:[['为何“废肉刑”仍可能造成新伤害？',[['替刑次数与执行方式失控会形成变相重刑','substance'],['刑名改变后实际后果不再重要','name'],['所有笞刑都必然轻于肉刑','assume']]],['如何建立改革反馈？',[['记录伤亡、复核执行并继续修订尺度','feedback2'],['隐去伤亡以维护诏令威信','hide2'],['出现问题即恢复全部肉刑','returnold']]]},3:{e:['坊门出入籍','崔安在案发后携包裹入坊，只能证明行动轨迹，不能直接证明包内是官帛。'],q:[['亲属容隐的边界如何判断？',[['区分不告发、虚假陈述与积极藏赃','acts'],['亲属身份使所有行为免责','absolute2'],['亲属关系本身就是犯罪','kincrime']]],['礼法结合体现在哪里？',[['国家规范吸收亲属伦理并同时设置边界','rituallegal'],['礼与法互不相关','separateall'],['只有礼没有成文规范','onlyritual']]]},4:{e:['药渣验状','药渣无致命毒物，削弱“投毒后持刀”的原审叙事。'],q:[['检验材料应如何进入裁判？',[['与尸格、环境和证言形成可复核证据链','forensic'],['仵作一句话即可决定全案','expertabsolute'],['口供存在时无需检验','noscience']]],['翻异别勘的制度价值是什么？',[['由不同官司复查，降低原审自我维护造成的错误','independent'],['翻供者自动无罪','autofree'],['只给原审知县再问一次','samejudge']]]},5:{e:['沈氏族谱与户籍','族叔并非素娘父母或法定尊长，其主婚权限本身存在疑问。'],q:[['如何在明代制度内处理本人陈词？',[['把陈词与主婚权限、婚书及聘财一并审查','context'],['直接宣布适用现代婚姻法','presentism'],['本人意见在任何情况下都无意义','silencewoman']]],['两份婚书如何处理？',[['分别核验成立时间、主婚权限、聘财和伪造行为','twodocs'],['聘财更多者当然有效','highest'],['交由宗族私下决定','private']]]},6:{e:['亲邻甘结','邻里证明周母年老无养，但只能支持留养审查，不能回答杀人事实。'],q:[['“事实不清”与“可矜”有何区别？',[['前者关系是否定罪，后者是在事实成立后的情节评价','distinguish'],['二者都是直接赦免','sameall'],['可矜可以代替事实审查','mercyfact']]],['秋审为何兼具两面性？',[['既提供慎刑复核，也体现皇权最终裁决','twosides'],['只是普通地方上诉','localappeal'],['完全由民间宗族决定','clanreview']]]},7:{e:['各国刑律译稿','译稿提供近代法典技术，但各国制度背景并不相同，不能直接复制。'],q:[['法律移植应如何进行？',[['比较制度背景，转化规则并说明本土适用理由','translate'],['逐字照搬即可自动生效','copyall'],['拒绝一切外来法律技术','rejectall']]],['修律与司法主权是什么关系？',[['修律是收回治外法权的重要条件之一，但不是自动交换','condition'],['公布新律即可立即撤废领事裁判权','automatic'],['二者完全没有关系','unrelated']]]}};
*/
const EXTRA2=[null,
 {e:['县署施行牒','县令曾批示“连坐须核实知情与藏匿”，证明基层并非只能机械株连。'],q:[['如何理解什伍连坐的历史作用？',[['它强化编户互监与国家控制，同时扩大身份连带责任','history'],['它与现代个人责任完全相同','modern'],['它只有道德劝善作用','moral']]],['法令信用如何维持？',[['奖罚标准公开且政府也受承诺约束','promise'],['不断加重刑罚即可','terror'],['允许官吏随时改变标准','arbitrary']]]]},
 {e:['诏令改制草案','草案把黥劓改为笞刑，却未细定次数与行刑规范。'],q:[['为何“废肉刑”仍可能造成新伤害？',[['替刑次数与执行方式失控会形成变相重刑','substance'],['刑名改变后实际后果不再重要','name'],['所有笞刑都必然轻于肉刑','assume']]],['如何建立改革反馈？',[['记录伤亡、复核执行并继续修订尺度','feedback2'],['隐去伤亡以维护诏令威信','hide2'],['出现问题即恢复全部肉刑','returnold']]]]},
 {e:['坊门出入籍','崔安在案发后携包裹入坊，只能证明行动轨迹，不能直接证明包内是官帛。'],q:[['亲属容隐的边界如何判断？',[['区分不告发、虚假陈述与积极藏赃','acts'],['亲属身份使所有行为免责','absolute2'],['亲属关系本身就是犯罪','kincrime']]],['礼法结合体现在哪里？',[['国家规范吸收亲属伦理并同时设置边界','rituallegal'],['礼与法互不相关','separateall'],['只有礼没有成文规范','onlyritual']]]]},
 {e:['药渣验状','药渣无致命毒物，削弱“投毒后持刀”的原审叙事。'],q:[['检验材料应如何进入裁判？',[['与尸格、环境和证言形成可复核证据链','forensic'],['仵作一句话即可决定全案','expertabsolute'],['口供存在时无需检验','noscience']]],['翻异别勘的制度价值是什么？',[['由不同官司复查，降低原审自我维护造成的错误','independent'],['翻供者自动无罪','autofree'],['只给原审知县再问一次','samejudge']]]]},
 {e:['沈氏族谱与户籍','族叔并非素娘父母或法定尊长，其主婚权限本身存在疑问。'],q:[['如何在明代制度内处理本人陈词？',[['把陈词与主婚权限、婚书及聘财一并审查','context'],['直接宣布适用现代婚姻法','presentism'],['本人意见在任何情况下都无意义','silencewoman']]],['两份婚书如何处理？',[['分别核验成立时间、主婚权限、聘财和伪造行为','twodocs'],['聘财更多者当然有效','highest'],['交由宗族私下决定','private']]]]},
 {e:['亲邻甘结','邻里证明周母年老无养，但只能支持留养审查，不能回答杀人事实。'],q:[['“事实不清”与“可矜”有何区别？',[['前者关系是否定罪，后者是在事实成立后的情节评价','distinguish'],['二者都是直接赦免','sameall'],['可矜可以代替事实审查','mercyfact']]],['秋审为何兼具两面性？',[['既提供慎刑复核，也体现皇权最终裁决','twosides'],['只是普通地方上诉','localappeal'],['完全由民间宗族决定','clanreview']]]]},
 {e:['各国刑律译稿','译稿提供近代法典技术，但各国制度背景并不相同，不能直接复制。'],q:[['法律移植应如何进行？',[['比较制度背景，转化规则并说明本土适用理由','translate'],['逐字照搬即可自动生效','copyall'],['拒绝一切外来法律技术','rejectall']]],['修律与司法主权是什么关系？',[['修律是收回治外法权的重要条件之一，但不是自动交换','condition'],['公布新律即可立即撤废领事裁判权','automatic'],['二者完全没有关系','unrelated']]]]}
];
EXTRA2.slice(1).forEach((x,k)=>{const c=V[k+1];c.evidence.push(x.e);c.court.push(...x.q)});
paint=function(){document.getElementById('vAct').textContent=`第${'二三四五六七八'[S.i-1]}卷 · ${C.era} · ${actNames[S.act]}`;document.getElementById('vGoal').textContent=[`理解${C.theme}`,`研判四件材料的证明力与局限`,`用证据检验对立人物的主张`,`选择当时制度中的处理路线`,`完成五轮正式审理并形成结局`][S.act];document.getElementById('vNoteCount').textContent=S.notes.length;[0,1,2,3,4].forEach(i=>document.getElementById('vP'+i).className=i<S.act?'done':i===S.act?'now':'')};
introTalk=function(){dialogue([['旁白',C.intro[0]],[C.role,C.intro[1]],[C.conflict[0],C.conflict[1]],[C.role,'面对他的主张，你首先关注什么？',[[`先核对制度依据，不能只看身份与声势`,'basis','知识节点：规范依据与人物立场应当区分'],[`先服从权势较高的一方`,'status','知识节点：身份不能替代事实和规范审查'],[`先按现代制度直接作答`,'present','知识节点：避免脱离时代语境']]], [C.conflict[2],C.conflict[3]],[C.role,'你决定以何种路径进入案件？',C.crisis.map(x=>[x[0],x[1],x[2]])],['旁白','你的立场已经写入案卷。接下来，任何判断都必须接受物证检验。']],()=>unlock([0,1],finish))};
investigate=function(){stage(`<section class="av-workbench"><header><div><small>${C.era} · 案例模拟</small><h1>${C.title}</h1><p>${C.intro[1]}</p></div><b>证据 ${S.evidence.length}/4</b></header><div class="av-columns"><aside><h3>涉案立场</h3><article><b>${C.conflict[0]}</b><span>${C.conflict[1]}</span></article><article><b>${C.conflict[2]}</b><span>${C.conflict[3]}</span></article></aside><main><h3>证据材料 <small>按顺序研判证明力</small></h3><div class="av-evidence-grid">${C.evidence.map((x,i)=>`<button ${i>S.evidence.length?'disabled':''} class="${i<S.evidence.length?'found':''}" onclick="avEvidence(${i})"><i>${i+1}</i><b>${x[0]}</b><span>${i<S.evidence.length?'已研判 · 可复核':i===S.evidence.length?'点击研判':'前件未完成'}</span></button>`).join('')}</div><div class="av-tip"><b>本卷制度焦点</b><p>${C.theme}</p></div></main><aside><h3>法脉札记</h3>${C.notes.slice(0,3).map((n,i)=>`<article class="${S.notes.includes(i)?'on':''}"><b>${S.notes.includes(i)?n[0]:'尚未解锁'}</b><span>${S.notes.includes(i)?n[1]:'推进剧情后显示'}</span></article>`).join('')}</aside></div></section>`)};
evidence=function(i){if(i>S.evidence.length)return;const e=C.evidence[i];modal(`<small>第 ${i+1}/4 件物证 · 先判断后收入</small><h1>${e[0]}</h1><p>${e[1]}</p><h2>这件材料应当怎样使用？</h2><div class="av-proof"><button onclick="avJudge(${i},'chain')">限定其证明对象，并与其他材料互证</button><button onclick="avJudge(${i},'absolute')">凭这一件材料直接认定全案</button><button onclick="avJudge(${i},'discard')">材料不能单独定案，所以完全排除</button></div><button onclick="avClose()">暂不收入</button>`)};
window.avJudge=(i,x)=>{if(!S.evidence.includes(i))S.evidence.push(i);S.choices.push(`e${i}_${x}`);save();modal(`<small>证据反馈</small><h1>${x==='chain'?'研判成立':'注意证明边界'}</h1><p>${x==='chain'?'你区分了材料能证明什么、不能证明什么，并把它放入证据链。':'不能把单件证据绝对化，也不能因为它需要互证就直接排除。'}</p><button class="primary" onclick="avContinueEvidence()">收入案卷并继续</button>`)};
continueEvidence=function(){close();if(S.evidence.length===4)unlock([2,3],finish);else run()};
confrontTalk=function(){dialogue([[C.role,`四件材料分别涉及：${C.evidence.map(x=>x[0]).join('、')}。它们必须互相校验。`],[C.conflict[0],C.conflict[1]],[C.conflict[2],C.conflict[3]],[C.role,'对质之后，你如何组织事实？',[[`区分无争议事实、相互矛盾之处和仍待证明的问题`,'factmap','知识节点：证据链不是材料的简单堆叠'],[`只采用支持预设结论的材料`,'confirm','知识节点：警惕选择性采证'],[`以人物品行代替证据判断`,'character','知识节点：身份评价不能替代行为证明']]],[C.role,'事实范围已经划定。下一幕，你必须在当时制度中选择处理路径。']],finish)};
court=function(){stage(`<section class="av-courtboard"><header><small>${S.i===7?'修订法律馆 · 正式表决':'模拟法庭 · 正式裁断'}</small><h1>${C.title}</h1><p>五轮回应将把时代语境、人物立场、物证与制度知识写成最终裁断。</p></header><div class="av-court-steps">${C.court.map((q,i)=>`<span><i>${i+1}</i>${q[0]}</span>`).join('')}</div><button class="primary" onclick="avCourtTalk()">开始五轮审理</button></section>`)};
courtTalk=function(){const lines=[];C.court.forEach((q,n)=>{lines.push([n===C.court.length-1?'主审者':C.conflict[n%2===0?0:2],q[0]]);lines.push([C.role,'你的回应是——',q[1].map(x=>[x[0],x[1],`第${n+1}轮 · 选择将影响最终结局`])])});dialogue(lines,()=>unlock([4,5],resolve))};
start=function(i){C=V[i];S=load(i);S.visited=S.visited||[];shell();if(S.savedAt&&(S.act||S.evidence.length||S.ending||S.visited.length))modal(`<small>发现分卷存档</small><h1>继续《${C.title}》？</h1><p>已完成场景 ${S.visited.length}/2 · 物证 ${S.evidence.length}/4 · 法脉札记 ${S.notes.length}/6</p><button class="primary" onclick="avRun()">继续存卷</button><button onclick="avRestart()">重新开始</button>`);else run()};
run=function(){close();paint();if(S.ending)return ending();if(S.act===0)return intro();if(S.act===1)return routeMap();if(S.act===2)return confront();if(S.act===3)return crisis();court()};
intro=function(){stage(`<section class="d-platform av-guide"><nav class="d-side"><h2>律令山河录</h2><button class="on">时代导学</button><button>人物会面</button><button>案卷调查</button><button>模拟法庭</button><button onclick="avNotes()">法脉札记</button></nav><div class="d-platform-main"><header><small>第${'二三四五六七八'[S.i-1]}卷 · ${C.era}</small><h1>${C.title}</h1></header><section class="d-overview"><div><small>你的身份 · ${C.role}</small><h2>${C.theme}</h2><p>${C.intro.join('')}</p></div><aside><b>本卷学习目标</b>${C.notes.slice(0,3).map(n=>`<span>${n[0]}</span>`).join('')}</aside></section><div class="d-module-grid"><article><i>史</i><b>时代背景</b><span>${C.intro[0]}</span></article><article><i>人</i><b>核心人物</b><span>${C.conflict[0]} · ${C.conflict[2]}</span></article><article><i>案</i><b>制度争点</b><span>${C.theme}</span></article><article><i>证</i><b>四件物证</b><span>${C.evidence.map(x=>x[0]).join('、')}</span></article><article><i>审</i><b>五轮审理</b><span>事实、规则、程序与制度后果</span></article><article><i>结</i><b>分支结局</b><span>选择形成判词，不设置分数等级</span></article></div><footer class="d-enter"><p>本卷采用“人物立场—证据研判—制度适用—历史后果”的完整互动结构。</p><button class="primary" onclick="avIntroTalk()">以${C.role}身份入卷</button></footer></div></section>`)};
function routeMap(){const metA=S.visited.includes('a'),metB=S.visited.includes('b'),ready=metA&&metB;stage(`<section class="d-map av-route-map"><div class="d-map-title"><small>${C.era} · 案卷行旅图</small><h1>${C.title}</h1><p>先完成两场人物会面，再进入案卷现场研判四件物证。</p></div><div class="d-route"></div><button class="d-place ${metA?'done':''}" style="left:18%;top:62%" onclick="avVisit('a')"><i>1</i><b>${C.conflict[0]}</b><span>听取制度主张</span></button><button class="d-place ${metB?'done':''}" style="left:45%;top:28%" onclick="avVisit('b')"><i>2</i><b>${C.conflict[2]}</b><span>听取相反立场</span></button><button class="d-place ${ready?'':'locked'}" style="left:73%;top:58%" onclick="avVisit('e')"><i>3</i><b>案卷调查处</b><span>${ready?'研判四件物证':'先完成人物会面'}</span></button><button class="d-place locked" style="left:48%;top:80%"><i>4</i><b>${S.i===7?'修律馆':'正式审理堂'}</b><span>收集证据后开放</span></button><aside class="d-map-log"><b>本卷进度</b><span>人物会面 ${S.visited.length}/2</span><span>物证 ${S.evidence.length}/4</span><span>知识节点 ${S.notes.length}/6</span></aside></section>`)};
window.avVisit=id=>{if(id==='e'){if(!(S.visited.includes('a')&&S.visited.includes('b')))return modal('<h1>前序未完成</h1><p>请先听取两方人物的完整主张。</p><button onclick="avClose()">返回地图</button>');return investigate()}const first=id==='a',person=first?C.conflict[0]:C.conflict[2],claim=first?C.conflict[1]:C.conflict[3];dialogue([[person,claim],[C.role,`你主张的依据是什么？若与物证冲突，是否愿意接受复核？`],[person,first?'制度若失去威信，执行便会动摇；但我愿看你拿出的材料。':'我并非请求法外开恩，只要求把身份、行为与证据分别判断。'],[C.role,'你如何记录这次会面？',[[`记录其制度理由，同时保留证据复核`,'meet_reason','知识节点：人物立场不能替代证据'],[`因其身份较高，直接采纳全部主张`,'meet_status','知识节点：身份不能自动决定事实'],[`只按个人好恶评价，不记录制度依据`,'meet_moral','知识节点：历史评价需要时代语境']]],[person,'我会在正式审理中等待你的回应。']],()=>{if(!S.visited.includes(id))S.visited.push(id);save();routeMap()})};
ending=function(){const d=C.endings[S.ending]||C.endings.weak;stage(`<section class="d-ending av-ending"><div class="d-end-scroll"><small>第${'二三四五六七八'[S.i-1]}卷剧情结局</small><h1>${d[0]}</h1><p class="lead">${d[1]}</p><div class="d-tabs"><button class="on" onclick="avEndTab(this,'learn')">我学会了什么</button><button onclick="avEndTab(this,'route')">我的选择轨迹</button><button onclick="avEndTab(this,'boundary')">史实边界</button></div><div id="avEndPanel"></div><div class="d-end-actions"><button class="primary" onclick="avComplete()">归档并返回八案</button><button onclick="avRestart()">重开本卷</button><button onclick="avNotes()">查看法脉札记</button></div></div></section>`);window.avEndTab(document.querySelector('.d-tabs button'),'learn')};
window.avEndTab=(btn,type)=>{document.querySelectorAll('.d-tabs button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');const p=document.getElementById('avEndPanel');if(type==='learn')p.innerHTML=`<h2>本卷知识总结</h2><div class="d-know-grid">${C.notes.map(n=>`<article><b>${n[0]}</b><span>${n[1]}</span></article>`).join('')}</div>`;if(type==='route')p.innerHTML=`<h2>选择轨迹</h2><p>人物会面 ${S.visited.length}/2 · 物证研判 ${S.evidence.length}/4 · 正式审理 ${C.court.length}轮</p><ol>${S.choices.map(x=>`<li>${x}</li>`).join('')}</ol>`;if(type==='boundary')p.innerHTML=`<h2>史实与教学化虚构</h2><p>${C.notes.map(n=>n[0]).join('、')}属于本卷法制史知识范围；具体人物对话、证据组合和审理程序为教学化虚构，用于帮助理解${C.theme}。</p>`};
dialogue=function(lines,cb){stage(`<section class="av-character-scene i${S.i}"><div class="av-scene-label"><small>${C.era} · ${actNames[S.act]}</small><h1>${C.title}</h1><p>${S.act===0?'人物将带你进入真实的制度争论。':S.act===2?'让物证检验双方人物的主张。':S.act===4?'正式审理中的每次回应都会改变结局。':'听取人物立场并记录其制度依据。'}</p></div><div class="av-person left p${S.i%4}"></div><div class="av-person right p${(S.i+2)%4}"></div><div class="av-scene-place">${S.act===0?'时代入局':S.act===2?'人物对质':S.act===4?(S.i===7?'修律馆':'正式审理堂'):'人物会面'}</div></section>`);Q=lines.slice();done=cb;nextLine()};
nextLine=function(){if(!Q.length){hide();const f=done;done=null;if(f)f();return}const l=Q.shift(),d=document.getElementById('vDialog');d.classList.remove('hidden');document.getElementById('vSpeaker').textContent=l[0];document.getElementById('vText').textContent=l[1];const cast=document.querySelector('.av-character-scene');if(cast){const mine=l[0]===C.role;cast.querySelector('.left')?.classList.toggle('dim',!mine);cast.querySelector('.right')?.classList.toggle('dim',mine)}const b=document.getElementById('vChoices');b.innerHTML='';document.getElementById('vNext').hidden=!!l[2];if(l[2])l[2].forEach((x,i)=>{const y=document.createElement('button');y.innerHTML=`<b>${String.fromCharCode(65+i)}</b>${x[0]}<small>${x[2]}</small>`;y.onclick=e=>{e.stopPropagation();S.choices.push(x[1]);save();nextLine()};b.appendChild(y)})};
/* 第二至第八卷脚本定稿：每卷独立人物、地图、证物边界与完整结局 */
const FINAL=[null,
 {scenes:['咸阳南门','县邑里门','县署案房','县廷决狱'],people:['木夫季','变法令史','里正','赵母','韩甲'],opening:[['木夫季','我不过把木头从南门搬到北门。众人都说官府不会真给重赏——县令，告示上的赏格还算数吗？'],['秦县令','新法第一次面对百姓，你如何兑现南门之赏？',[[`足额兑现，并把赏券和给付过程公开记入簿册`,'reward_full','政府先履行自己公布的承诺'],[`赏金太高，临时减半`,'reward_half','官府自行改变公开标准'],[`只给口头表彰，不给实赏`,'reward_words','法令承诺停留在文字上'],[`处罚围观者，以严刑显示新法威势`,'reward_fear','把信用误作单纯恐惧']]],['变法令史','赏已兑现，新法便应无所回避。赵武逃役归里，其母藏子，十户同伍，正当尽数连坐。'],['里正','两户当夜在外服驿役，根本不知赵武归来。若连不在场也同罚，百姓信的是法，还是官吏一句话？']],meet:[[['变法令史','什伍相保，一家藏奸，全伍有责。逐户核实知情，连坐之威便散了。'],['秦县令','威势能否代替事实？不在场者也应承担同样责任吗？'],['变法令史','新法求的是人人互察。责任若只落在藏匿者，旁人便会装作不知。']], [['里正','赵母确曾送饭藏子；但驿役册可证明两户不在里。韩甲的告书也夹着一桩争田旧怨。'],['秦县令','旧怨是否足以让整份告书失效？'],['里正','不能。真实线索要采用，借告奸诬陷的部分也要追究；否则奖励会变成私怨的刀。']]],evidence:[['南门赏券','券上写明木夫季徙木所得赏格，县府给付记录完整。','证明官府兑现承诺并建立初步信用。','不能证明以后任何严厉处罚都属于“守信”。'],['什伍名籍','十户被编为一伍，载有户主、亲属及互保关系。','证明身份编组和相互监督关系存在。','不能直接证明每户都知道赵武藏匿。'],['驿役记录','两户男子在案发前已奉命赴驿，归期晚于赵武被捕。','证明两户案发时不在里中。','不能反推其余住户必然知情。'],['韩甲告书','告发三户协助藏匿；田契显示韩甲与其中一户有争地旧怨。','提示告发动机复杂，必须逐项核验。','不能因此认定韩甲全部陈述都是虚假。']],boundary:'徙木立信、商鞅变法、什伍连坐和告奸属于法制史知识；赵武、赵母、韩甲及本县审理过程为教学化虚构。',stories:{good:'<h2>信与刑之间</h2><p>你足额兑现徙木赏格，又把十户分别询问。赵武依法受罚，赵母因积极藏匿承担责任；确实知情而不告者受罚，两户持驿役记录者获释。韩甲告书中的真实线索被采用，借争田旧怨捏造的部分则被追究。</p><h3>数月以后</h3><p>县中百姓仍畏惧新法，却渐渐相信公开的赏罚不会由官吏随意改变。里正说：“从前只怕官府，如今也会问官府是否照自己写下的规则办事。”连坐与告奸的严厉结构并未消失，但法令信用不再只来自恐惧。</p>',hard:'<h2>举里皆惧</h2><p>十户全部被罚，包括案发时远在驿站的住户。韩甲因告奸得赏，越来越多人学会用告书解决私怨。</p><h3>一年以后</h3><p>逃兵减少了，邻里也不再彼此信任。有人见邻人犯错，不再劝止，只等待换取赏赐的时机。县里看似安静，家家夜间却紧闭门户。</p>',weak:'<h2>法令失信</h2><p>你临时削减南门赏格，又在逃兵案中反复改变连坐标准。百姓发现告示写得再清楚，官府也能随时换一种说法。</p><p>有人不再相信告发会得赏，也有人相信行贿便可脱免。新法依旧严厉，却失去稳定；真正决定结果的，仍是官吏当日的态度。</p>'}},
 {scenes:['长安城门','廷尉狱署','刑制议堂','未央奏议'],people:['缇萦','廷尉正','淳于意','狱吏','河东使者'],opening:[['旁白','囚车穿过长安城门。淳于意将受肉刑，幼女缇萦一路追随，手中紧握写给天子的奏书。'],['缇萦','妾愿没入为官婢，以赎父刑。人受肉刑，身体残毁，即使愿意改过，也再没有恢复的机会。'],['廷尉府属官','你怎样接收这封奏书？',[[`把它作为对肉刑不可逆性的制度批评`,'petition_system','从个案进入刑罚目的'],[`只把它记作孝女救父`,'petition_filial','制度问题被缩成感人故事'],[`因女子议刑而拒收`,'petition_reject','身份阻断制度意见'],[`只求赦父，不讨论普遍规则`,'petition_pardon','个案恩赦不能代替改革']]],['廷尉正','肉刑沿用已久，见刑于身，足以禁奸。废之以后，凭什么使人畏惧？']],meet:[[['廷尉正','黥、劓、刖虽酷，却能使众人一望知戒。若改作笞刑，犯者岂不轻视国法？'],['廷尉府属官','刑罚目的只有威慑吗？永久伤残是否也堵死改过之路？'],['廷尉正','改革可以议，但若替刑无等差、执行无尺度，所谓仁政反会失去秩序。']], [['缇萦','我没有说父亲必然无罪。我说的是：一刀落下，改过也无法让鼻与足再生。'],['廷尉府属官','若废肉刑后，高额笞刑仍致人死伤呢？'],['缇萦','那就不应只庆祝刑名改变，还要把行刑后果写进奏报，让改革继续纠错。']]],evidence:[['缇萦奏书','奏书从父亲个案提出肉刑造成永久残毁、使人无由改过。','证明申诉包含普遍的刑罚制度批评。','不能证明淳于意在原案中必然无罪。'],['旧日行刑簿','簿中记有黥、劓、刖后长期伤残及无法复业者。','证明肉刑的伤害具有永久性。','不能仅凭刑罚残酷认定所有受刑者都是冤案。'],['替刑草案','草案拟以笞刑、徒刑代替肉刑，但部分罪名笞数极高，刑具与部位未定。','证明废刑方向尚未解决执行尺度。','不能因为名称较轻，就推定实际伤害必然较低。'],['河东伤亡奏报','新制试行后出现高额笞刑致死、致残记录。','证明替代刑的实际后果需要反馈和修正。','不能由局部伤亡直接否定废除肉刑的改革方向。']],boundary:'缇萦上书和汉文帝刑制改革具有史实基础；具体行刑簿、草案讨论和玩家参与方式为教学化设计。',stories:{good:'<h2>史官之笔</h2><p>肉刑被废，替代刑按罪责分等。你限制笞数、规定刑具与行刑部位，并要求各郡如实上报伤亡。淳于意获得重新审理，缇萦终于回到父亲身边。</p><h3>数年以后</h3><p>改革仍造成新的死伤，但数字没有被藏起来。朝廷据此继续调整笞刑。史官写道：“善法并非从不犯错，而是让错误被看见，并据此继续修正。”</p>',hard:'<h2>笞下新伤</h2><p>肉刑名称被废，所有罪行却统一改为高额笞刑。诏书宣称仁政已成，狱中却不断有人死于杖下。</p><p>他们没有被割鼻断足，也不再背负旧刑名，却仍未能活着走出刑场。形式改变了，实际伤害可能更加沉重。</p>',weak:'<h2>一人得赦</h2><p>你只帮助缇萦救下父亲，没有触动普遍制度。父女在长安城门相拥时，另一辆囚车正从他们身旁驶入。</p><p>车上犯人将承受同样的肉刑，却没有一个能够上书的女儿。恩赦改变了一家人的命运，规则依旧等待下一场偶然的仁慈。</p>'}},
 {scenes:['长安染坊','崔氏宅院','大理寺案库','大理寺法堂'],people:['崔安','崔六','库吏','邻人','大理寺博士'],opening:[['旁白','官帛在染坊失窃。崔六逃入兄长崔安家中，崔安拒绝告发，并称弟弟整夜在家；官差却在灶后发现被烧过的官帛碎片。'],['崔安','律许同居亲属相隐。我不亲手把弟弟送入官府，何罪之有？'],['大理寺评事','你先划定哪一道边界？',[[`区分不告发、虚假证明、藏赃、助逃和共同盗窃`,'kin_distinguish','亲隐必须对应具体行为'],[`兄弟同居便一门同罪`,'kin_same','身份替代行为调查'],[`亲属关系使一切协助免责`,'kin_absolute','有限容隐被扩成绝对屏障']]],['库吏','官帛出现在崔宅，兄弟又同居，还分什么行为？一并定罪最快。']],meet:[[['库吏','官帛是官物。崔六盗帛、崔安藏人藏物，兄弟同处一宅，何必再分？'],['大理寺评事','住宅发现碎片，只能证明什么？能否直接证明崔安参与最初盗窃？'],['库吏','不能直接证明，但若过度宽容亲隐，官物便会尽数藏进亲属家中。']], [['崔安','我是兄长，不告发弟弟是人伦。若连沉默也与盗窃同罪，亲属之义何在？'],['大理寺评事','沉默与编造不在场、焚毁官帛，是否仍是同一种行为？'],['崔安','我愿你依律分辨，但别因我姓崔、与他同居，就先把我写成盗犯。']]],evidence:[['染坊账簿','记载崔六案发时领取染料并进入官帛库旁工间。','证明崔六案发时曾在染坊活动。','不能单独证明他完成盗窃，更不能证明崔安参与。'],['崔安初供','初称崔六整夜在家，后又承认其深夜归宅，前后矛盾。','削弱崔六不在场说法，并提示虚假陈述。','不能仅凭供述矛盾认定兄弟共同盗窃。'],['官帛碎片','带官府织记的帛片在崔宅灶后发现，有焚烧痕迹。','支持赃物曾被带入住宅并可能遭隐藏、毁弃。','不能自动证明崔安知道来源或参与原盗。'],['邻里证言','邻人称深夜看见兄弟二人在灶前焚烧织物。','可与碎片和初供互证积极处理赃物。','不能排除夜色误认，也不能单独证明崔安参与盗取。']],boundary:'《唐律疏议》及亲属容隐属于历史制度；崔氏兄弟、官帛案和证据组合为教学化虚构。',stories:{good:'<h2>礼法有界</h2><p>你承认崔安不主动告发弟弟受亲属伦理保护，却分别审查虚假证明和藏匿官帛。崔六对盗帛负责；崔安不因兄长身份自动同罪，但因积极隐藏、毁弃赃物承担相应责任。</p><p>崔安问：“既允许相隐，为何我仍受罚？”你答：“容许你不亲手送弟入官，不等于允许你改变事实、毁灭证据。”礼被承认，却没有吞没行为责任。</p>',hard:'<h2>一门同罪</h2><p>你以兄弟同居为由将二人同罪。案件迅速结清，官帛也获追偿。此后，只要家中一人涉案，整户便先隐藏关系、逃离住所。</p><p>身份取代行为调查，办案更快，也更粗糙。</p>',weak:'<h2>亲隐无边</h2><p>你认为亲属关系可使全部协助免责。拒绝告发、编造证词、转移官帛和助逃都被装进“亲隐”二字。</p><p>越来越多盗犯把赃物送进亲属宅院。亲属伦理从有限容隐，变成逃避责任的绝对屏障。</p>'}},
 {scenes:['临安药圃','县衙验所','提刑司案房','别勘法堂'],people:['陆惟恭','原审知县','仵作','药圃管事','雨夜证人'],opening:[['旁白','赵员外死于雨夜药圃。赘婿陆惟恭在夹讯后认罪，又在押解途中翻供。县衙说短刀是凶器，尸格却只记颈部索沟。'],['陆惟恭','刀上无血，尸身无刀伤。我的口供是在刑具下照着县役的话说的。'],['提刑司属官','面对翻供，你先做什么？',[[`核对尸格、凶器、雨势和刑讯记录，决定是否别勘`,'review_chain','以外部证据检验口供'],[`有认罪便维持原审`,'keep_confession','口供压过客观矛盾'],[`翻供即视为当然无罪`,'auto_acquit','翻供也需要调查'],[`只找一名新证人替代口供`,'single_witness','从一个单证据跳到另一个']]],['原审知县','案犯已经画押。若每次翻供都重开案卷，县衙还如何结案？']],meet:[[['原审知县','陆惟恭先供投毒，再说持刀。供词虽有细节出入，终究已经认罪。'],['提刑司属官','尸格没有刀伤，短刀没有血迹。为何应让口供压过这些矛盾？'],['原审知县','刑讯是为得实。若凡受讯之供都疑，狱案将无从定夺。']], [['仵作','尸格写的是颈部索沟，不是刃伤。短刀像园中工具，雨夜证言也未必看得清脸。'],['提刑司属官','尸伤是否就能独自说出凶手？'],['仵作','不能。口供会看刑具脸色，尸伤不会；可尸伤仍要由人正确读取，并与现场、天气和证言互证。']]],evidence:[['尸格','死者颈部有连续索沟，没有刺切创口。','支持死因更接近绳索勒颈，并反驳短刀致命叙事。','不能单独确认凶手身份。'],['无血短刀','刀为药圃常用工具，刃上没有可见血迹。','削弱其作为直接致命凶器的可能。','不能证明刀从未被持拿，也不能仅凭无血排除所有用途。'],['雨势簿','目击者所称时辰正值暴雨，能见度极低。','削弱远距离辨认面容的可靠性。','不能证明目击者必然撒谎或现场无人经过。'],['刑讯记录','陆惟恭认罪发生在夹讯后，供述细节随问话多次改变。','提示口供可能迎合预设案情。','不能仅因受刑讯便当然认定被告无罪。']],boundary:'《洗冤集录》、尸格、检验和翻异别勘体现宋代司法知识；药圃案件及人物为教学化虚构。',stories:{good:'<h2>雨歇见痕</h2><p>你启动别勘，重新检验尸伤和现场。赵员外死于绳索勒颈，短刀只是园中工具；雨夜证人看到的“陆惟恭”，只是穿着相似蓑衣的人。</p><p>药材账目最终指向侵吞公款的管事。陆惟恭获释时问：“若没有尸格上的索沟，我的供词是否就会成为全部真相？”仵作答：“尸伤也要由人读懂，所以才要让证据彼此说话。”</p>',hard:'<h2>供词成狱</h2><p>你维持原审，陆惟恭被定罪。数年后，管事在另一案中供出雨夜旧案。</p><p>原卷重开时，短刀依然无血，尸格上的索沟也从未消失。错误不是没有留下痕迹，只是当时无人允许痕迹挑战口供。</p>',weak:'<h2>一言定罪</h2><p>你推翻口供，却完全依赖一名目击者改判他人。后来查明，证人在暴雨中根本无法看清面容。</p><p>案件从“唯口供”转为“唯一目击证言”，一个单一证据被推翻，另一个又占据全部真相。</p>'}},
 {scenes:['江南沈宅','县衙户房','官印库房','县堂听讼'],people:['沈素娘','沈族叔','陆家中人','赵家中人','户房书吏'],opening:[['旁白','沈素娘的族叔先后收取陆、赵两家聘财，两家今日同时持婚书到县衙。陆家文书上还有知县朱批，印文却与官样略有不同。'],['沈素娘','两份婚书都写着我的名字，却没有一句是我说的话。族叔还占着父亲留下的田产。'],['江南县丞','你怎样进入这宗婚案？',[[`分别核验主婚权限、两份婚书、聘财和官批真伪`,'marriage_layers','在明代制度内拆分问题'],[`聘财多者当然得婚`,'highest_bid','把婚姻完全当作财物交易'],[`直接宣布适用现代婚姻自由`,'modern_only','价值清楚却跳过历史规范'],[`交回宗族，不问伪造官批`,'clan_return','家族权力覆盖官府文书问题']]],['沈族叔','孤女婚事本应由族中长者作主。我为宗族筹措用度，收两家聘财又有何妨？']],meet:[[['沈族叔','父母既亡，族中长辈自然主婚。陆赵两家皆是良配，择聘财丰厚者有何不可？'],['江南县丞','你是否具有主婚权限？两次收聘、占用家产又如何解释？'],['沈族叔','那是宗族内部之事，县衙不应把家礼拆成几宗罪责。']], [['沈素娘','我知道当时不是人人都能自己定婚，但族叔不是父母，也不能拿同一桩婚事收两次钱。'],['江南县丞','你希望哪些话进入正卷？'],['沈素娘','写清我从未参与订约、官批并非我所求，也写清族叔一直控制我的田产。别让案卷只剩两张婚书。']]],evidence:[['两家婚书','陆、赵两份婚书日期相近，主婚人均署沈族叔。','证明存在重复订约及主婚人身份。','不能仅凭文书外观判断两约效力或官批真伪。'],['两家聘财簿','族叔先后收受两家银、绢及礼物，部分已用于个人债务。','证明重复收聘及财物流向。','不能单独决定婚约归属。'],['县印样式簿','陆家婚书朱批印文的篆画、缺口与同期县印不符。','支持官批可能伪造，应另案追查。','不能仅凭一处差异直接锁定具体伪造者。'],['沈素娘陈词','陈述未参与两次订约、父母已亡、族叔控制家产。','支持审查主婚权限与财产关系，并使本人处境进入案卷。','不能直接以现代婚姻自主原则替代全部明代户婚规则。']],boundary:'明代户婚、父母主婚、婚书聘财和官文书规则属于历史制度；沈素娘案为教学化虚构。',stories:{good:'<h2>婚书之外</h2><p>你核验婚书、聘财和主婚权限，认定族叔无权私自处分婚事，却先后收取两家财物；陆家朱批由中间人伪造。</p><p>判词分别处理婚约效力、重复收聘、财物返还、伪造官文书和族叔侵占家产。素娘没有立刻获得现代意义上的完全婚姻自主，但她的陈述第一次完整进入正卷，不再只是两份婚书上的同一个名字。</p>',hard:'<h2>宗祠定婚</h2><p>你把案件交回宗族。族长决定素娘嫁给聘财较高的一方，伪造朱批不再追究。</p><p>几年后，族叔又以家族名义处分另一名孤女的婚姻和财产。官府维护了宗族秩序，也把文书伪造与重复收聘留在宗祠门外。</p>',weak:'<h2>越代判词</h2><p>你直接宣布婚姻必须完全由本人自由决定，却没有处理聘财、伪造朱批和族叔权限。</p><p>素娘暂时获救，两家仍为财物争执，伪造者也未担责。判词符合现代价值，却无法说明它在明代案卷中如何适用。</p>'}},
 {scenes:['刑部秋审处','原审卷库','仵作复核房','秋审大堂'],people:['周成','周母','原审知县','秋审司官','关键证人'],opening:[['旁白','周成因械斗致死被判斩监候，原审拟列“情实”。秋审前，证人翻供，供词上有刑讯记号，尸伤方向又与所报凶器不符。'],['周母','他是独子。我求的不是因他要养我便说他无罪，只求先把事实查清，再谈他该不该留下。'],['秋审司官','你先审查哪一层？',[[`先核事实疑点，再分别考虑情节和留养`,'facts_first','事实、宽宥、家庭身份分层'],[`维护原审威信，直接列情实`,'confirm_real','既判压过不可逆风险'],[`独子身份足以直接留养`,'family_first','家庭身份覆盖事实判断'],[`把事实不清直接写成可矜`,'mix_categories','混淆证明与宽宥']]],['原审知县','案已定谳。若因一纸翻供便重开旧卷，地方官的威信何在？']],meet:[[['原审知县','周成已经认罪，凶器也已报部。秋审本为定类，不该替地方重做一遍审问。'],['秋审司官','供词为何有夹讯记号？致命伤方向为何与凶器相反？'],['原审知县','卷宗若处处可疑，天下死案何时才能执行？']], [['周母','我知道他参加了械斗，也不敢说他全无责任。可证人已经改口，伤痕也对不上。'],['秋审司官','若事实核清后仍有罪，你是否只主张留养？'],['周母','是。事实是事实，奉养是奉养。不能因他是独子就说无罪，也不能因他有老母就不看疑点。']]],evidence:[['刑讯供词','认罪供述形成于夹讯后，数处关键细节与问词顺序一致。','提示供词可能受刑讯和诱导影响。','不能因此当然认定周成未参与械斗。'],['仵作格目','致命创自右后方向斜入，与原报周成正面持刀的说法不合。','证明尸伤与指控方式存在重要矛盾。','不能单独确认真正实施致命伤者。'],['证人翻供书','关键证人称原供受到县役诱导，并请求重新对质。','使原证言可靠性受到动摇，应核查翻供原因。','不能把翻供自动等同真实陈述。'],['周氏户籍与奉养材料','周成为独子，母年老无其他成年奉养人。','支持进入留养承祀的身份与家庭审查。','不能回答杀人事实，也不能代替对致命伤的核验。']],boundary:'斩监候、秋审分类、可矜和留养承祀属于清代制度；周成案及证据组合为教学化虚构。',stories:{good:'<h2>红册缓勾</h2><p>你先审事实，再考虑家庭情节。案件列入缓决，证人重新对质，尸伤重新核验。调查显示周成参加械斗，但致命伤可能来自另一人。</p><p>周成没有立即获释，死刑也未当然取消，执行被暂缓。周母离开刑部时说：“我求的不是因他是独子便无罪，只求事实清楚以后，再谈他该不该留下。”秋审既体现皇权终裁，也成为纠正原审的第二道门。</p>',hard:'<h2>情实勾决</h2><p>你为维护既判与官府威信，维持情实。刑讯记号、尸伤矛盾和翻供没有进入最终题本。</p><p>数年后，另一名械斗者临死前承认自己造成致命伤。红册文字已经褪色，死刑却无法撤回。</p>',weak:'<h2>留养之门</h2><p>你直接因独子身份主张留养，没有审查事实疑点。周成得到暂缓，母亲获得奉养。</p><p>另一名案情和家庭情况相似的犯人，因无人代为陈情仍被列为情实。宗法孝养进入死刑审查，也可能使相同案件因家庭身份得到不同结果。</p>'}},
 {scenes:['修订法律馆','礼法会议厅','各省司法档案室','新刑律表决厅'],people:['沈家本','礼教派大臣','外务官','外国顾问','报馆记者'],opening:[['旁白','清末修订法律馆。新刑律草案试图区分犯罪与道德、减少比附；礼教派担心亲属名分动摇，外务官又希望借修律收回领事裁判权。'],['沈家本','刑律应限定国家刑罚权。若一切不合伦理之事都入刑，刑法便没有尽头。'],['修订法律馆参议','你以何种原则审读草案？',[[`逐条区分犯罪、伦理评价与过渡规范，并公开理由`,'modern_transition','把边界写进制度'],[`传统伦理全部原样入刑`,'all_ritual','法典更名而结构不变'],[`完全照搬外国法典`,'copy_foreign','技术文本脱离实施条件'],[`只为换取列强承认而修律`,'foreign_exchange','把主权误作法典交易']]],['礼教派大臣','中国以亲属名分立国。新律若只论抽象个人，不论尊卑亲疏，这又是谁的法律？']],meet:[[['礼教派大臣','伦理并非私德。亲属名分维系家国秩序，刑律若尽数删除相关规范，社会凭什么维持？'],['修订法律馆参议','哪些行为具有严重社会危害，哪些主要属于伦理评价？可否逐条说明，而不是把所有争议一次入刑？'],['礼教派大臣','我反对的不是文字整齐，而是移植时把本国社会关系一并抹去。']], [['沈家本','近代刑法体例可以限制比附、明确罪刑，但外国条文不能逐字落地。各省法院、监狱和人才尚未齐备。'],['修订法律馆参议','修律能否直接换回领事裁判权？'],['沈家本','修律是收回司法主权的重要条件之一，不是自动交换。文本、机构、人才和实际审判能力必须一同改变。']]],evidence:[['新刑律草案','采用近代专门刑法典体例，重构犯罪、主刑从刑并减少比附。','证明法典技术和刑罚体系正在转型。','不能证明新制度已经具备全面实施条件。'],['礼教派签注','逐条反对删除部分亲属伦理规范，并提出社会秩序理由。','证明礼法之争涉及法律与伦理边界。','不能把所有意见简单视为无知守旧，也不能证明传统规范都应入刑。'],['领事裁判照会','列强以司法制度为由拒绝立即放弃领事裁判权。','证明修律与国家司法主权目标相关。','不能证明照搬外国法典即可自动收回主权。'],['各省司法报告','多省报告审判机构、监狱条件和新法人才不足。','证明法典改革必须考虑实施能力与过渡安排。','不能因此认定近代法典改革毫无必要。']],boundary:'《大清新刑律》、礼法之争与领事裁判权问题有史实依据；会议对话、具体签注组合和玩家表决为教学化设计。',stories:{good:'<h2>新律未竟</h2><p>你采用近代刑法体例，明确犯罪与刑罚边界；对部分伦理争议设置过渡规范，并公开修改理由。</p><p>新律在争论和妥协中完成，却未及在清朝充分实施，王朝便走向终结。修订馆关闭前，老参议抚着草案说：“我们没有完成一个时代，却改变了后人讨论刑法时使用的语言。”它没有立即解决治外法权和司法能力，却影响了此后的刑法道路。</p>',hard:'<h2>旧律新名</h2><p>你保留旧律主要伦理和身份结构，只改变名称与部分刑罚。反对声音暂时减少，新法却仍大量依赖旧有比附和身份规范。</p><p>外国使节认为中国只是换了法典外观。法典有了新名字，制度仍生活在旧秩序中。</p>',weak:'<h2>纸上主权</h2><p>你完全照搬外国法典，希望迅速获得列强承认。外国顾问称赞技术先进，各省官员却不知如何适用，监狱、审判机关和人才也未同步改革。</p><p>领事裁判权没有立即撤废。你终于明白：法律近代化与国家主权相连，却不能用一部翻译法典直接交换主权。</p>'}}
];
FINAL.slice(1).forEach((d,i)=>{const c=V[i+1];Object.assign(c,d);c.evidence=d.evidence;c.stories=d.stories});
const SECOND_FINAL={
 era:'战国·秦孝公变法初期',role:'杜县新任县令',theme:'徙木立信、什伍连坐、告奸与诬告',
 scenes:['栎阳南门','杜县赵宅','杜县县署案房','杜县里门法堂'],people:['季良','卫成','田伯','孟媪','韩甲'],
 opening:[
  ['旁白','新法颁布前，栎阳南门立起三丈高木。告示悬赏搬至北门者，百姓却怀疑这是官府设下的陷阱。'],
  ['季良','我已把木头搬到北门。告示写的是重赏，官府真的不会反悔吗？'],
  ['杜县新任县令','赏金发放前，你提出什么意见？',[[`足额兑现，并把赏券、给付和见证者公开记入簿册`,'reward_full','赏罚必信首先约束政府承诺'],[`赏格过高，临时减半`,'reward_half','公开标准被官府自行改变'],[`只给荣誉，不给实赏`,'reward_words','徙木失去兑现承诺的意义'],[`以贪利、扰乱城门为由处罚季良`,'reward_trap','告示被理解为官府陷阱']]],
  ['卫成','赏既写明，便不可少一金；刑既公布，也不可因人增减。三日后，新法将随驿骑送到杜县。'],
  ['旁白','黄昏，孟媪跪在杜县衙门前，承认藏匿逃兵之子赵武。韩甲几乎同时递上告书，声称田伯、孙乙、陈家乃至整伍都曾相助。'],
  ['卫成','新法入县第一案，若不迅速全伍收押，人人都会说自己不知。连坐还有什么威势？'],
  ['杜县新任县令','你怎样处置十户？',[[`暂记全伍，夜搜赵宅后分别调查知情、藏匿和不在场`,'detain_investigate','执行新法同时核查责任基础'],[`立即将全伍十户收押`,'detain_all','威慑迅速但身份替代事实'],[`只追究赵武，不调查任何他人`,'only_deserter','忽略当时匿奸与互监结构']]],
  ['孟媪','是我给了他饭，把他藏在柴房。孙乙只知道有人受寒，陈家当夜根本不在杜县。罪在老妇，不能让未见过他的人同罚。']
 ],
 meet:[
  [['卫成','什伍相保，一家藏奸，全伍有责。若逐户核实知情，连坐之威便散了。'],['杜县新任县令','严格执行是否等于不调查事实？人在河西服役，也要当作当夜协助吗？'],['卫成','新法初行，迟疑会被看成软弱。但若官府允许虚假告书换赏，新法同样会失去信用。'],['卫成','你若坚持调查，就必须给出一套能稳定执行、而非临时开恩的标准。']],
  [['田伯','孙乙承认送过冬衣，却说不知道给谁；陈家兄弟有河西驿役记录。韩甲与陈家争田，还曾威胁等新法下来便让他们离开。'],['杜县新任县令','韩甲确实帮助找到赵武，这是否使他其余陈述都可信？'],['田伯','不。真实部分可以采用，虚构部分也要追究。否则百姓学会的不是告奸，而是借法害人。'],['孟媪','我不求亲情使我无罪，只求别把我的知情写到所有邻人的名下。']]
 ],
 evidence:[
  ['南门赏券','季良已依告示取得全额赏金，给付过程有官吏记录和百姓见证。','官府通过兑现公开奖赏建立了新法的初步信用。','不能证明对所有嫌疑人施以重罚都是守信，也不能证明连坐越广信用越高。'],
  ['什伍名籍','赵、韩、孙、陈等十户同编一伍；田伯负责登记，赵韩及韩陈之间均有田界争议记录。','证明各户处于同一基层互监关系，也提示部分告发存在利益冲突。','不能直接证明每户都知情、共同藏匿或掌握相同信息。'],
  ['驿役和徭役记录','陈家兄弟在赵武返乡前十日已赴河西服役，驿站出入记录显示案发后方归。','证明陈家关键时段不在杜县，并与“当夜助逃”的告发冲突。','不能证明陈家此前从未与赵武联系，也不能证明韩甲其他告发全假。'],
  ['韩甲告书与田契','告书称赵、孙、陈三家共同藏匿；田契显示韩甲与陈家争夺水渠旁土地，并曾扬言借新法逼迁。','证明韩甲可能具有报复动机，对陈家指认必须逐项核验。','不能因存在旧怨就排除全部陈述，也不能否认赵武确曾藏在赵宅。']
 ],
 crisis:[
  ['同伍十户一律同罚','all','身份连带优先，不再区分实际知情与履行条件'],
  ['分别审查知情、藏匿、不在场与诬告','bounded','不取消秦法结构，但核实每项责任基础'],
  ['亲属藏匿出于亲情，一律无罪','kin_free','符合现代情感却脱离秦法匿奸背景'],
  ['所有告发都有利国家，不问真假','inform_all','告发数量优先，私人报复不受约束']
 ],
 court:[
  ['新法信用主要来自什么？',[[`政府按照公开标准履行赏与罚的承诺`,'trust'],[`处罚人数足够多、刑罚足够重`,'fear'],[`官吏拥有随时改变标准的自由`,'arbitrary'],[`只需兑现赏格，处罚标准可以变化`,'reward_only']]],
  ['什伍关系在本案中意味着什么？',[[`是调查监督义务的起点，不自动等于共同犯罪`,'relation_start'],[`同伍身份直接证明所有人共同藏匿`,'all'],[`完全废除什伍，不问当时制度`,'abolish_modern'],[`只罚最贫弱一户以示警`,'scapegoat']]],
  ['韩甲部分真告、部分虚告，怎样处理？',[[`真实部分按标准给赏，虚构部分另行追究`,'verify_split'],[`找到赵武有功，其余谎言不必追究`,'inform_all'],[`有私人恩怨，全部陈述一律无效`,'discard_all'],[`先足额奖励，再封存告书不核验`,'reward_all']]],
  ['陈家案发时在河西服役，是否连坐？',[[`核实其知情可能与报告条件，采纳可靠不在场记录`,'absence_check'],[`同伍即同罚，人在何处并不重要`,'all'],[`名籍和驿役记录都不能作为证据`,'ignore_records'],[`凡自称不知者全部释放`,'release_claim']]],
  ['请提交最终执行方案。',[[`公开奖罚标准，分别记录知情、藏匿、诬告和不在场`,'public_records'],[`整伍同罚，迅速建立威势`,'all'],[`根据官吏个人印象临时处置`,'arbitrary'],[`取消一切告奸与基层互监`,'abolish_modern']]]
 ],
 notes:[['徙木立信','重点在政府兑现公开承诺，使百姓相信后续赏罚会稳定执行。'],['赏罚必信','有罪必罚、有功必赏，也意味着政府不能随意反悔或因人改变。'],['什伍编制','掌握户籍、赋役与兵役，并把国家监督深入基层社会。'],['连坐制度','以身份和监督关系扩大责任，可降低调查成本，也可能牵连不知情者。'],['告奸与诬告','告奸增加国家信息，但若不核验和追究虚告，会诱发私人报复。'],['历史评价边界','应先理解秦法的国家动员逻辑，再与现代个人责任原则比较。']],
 endings:{good:['信与刑之间','你兑现赏格，并在秦法结构内区分逃兵、积极藏匿、可能不知情、不在场和虚假告发。'],hard:['举里皆惧','整伍因身份一律受罚，告发数量激增，邻里信任被自保性告发取代。'],weak:['法令失信','赏格和连坐标准反复改变，百姓不再读告示，只打听官吏当日态度。'],snow:['告书如雪','所有告发都获奖励，真假无人核验；案房得到海量信息，却逐渐无法分辨真实。']},
 stories:{
  good:'<h2>信与刑之间</h2><p>县衙当众宣读：赵武无令离营，承担逃亡责任；孟媪明知其身份仍藏于柴房，按积极藏匿处理。孙乙确曾送衣，但现有材料不能证明他知道衣物交给逃兵。陈家兄弟有河西驿役记录，韩甲关于二人“当夜助逃”的说法不予采信。</p><p>卫成问：“韩甲既有真告也有假告，究竟赏还是罚？”你答：“真实部分依公开标准兑现，虚构部分依其行为追究。若一项真告可以遮蔽其余谎言，奖励的便不是告奸，而是借法害人。”</p><h3>一个月后</h3><p>韩甲得到找到赵武的奖赏，同时因虚构陈家参与被追责。田伯在名籍后增列：是否在县、是否知情、是否有报告条件、是否实施藏匿、告发是否核实。</p><h3>半年后</h3><p>杜县告发数量没有邻县多，查实率却更高。季良把南门赏金铸成小环挂在木车上：“我搬的是一根木头。真正被搬动的，是百姓对官府告示的看法。”新法仍严厉并强化国家控制，但信用不再只来自恐惧。</p>',
  hard:'<h2>举里皆惧</h2><p>十户全部被收押。陈家举起河西驿役记录，卫成只答：“连坐问的是同伍身份，不是每个人的脚在何处。”孙乙不知道冬衣交给谁，也被视为推卸。韩甲的虚假部分无人调查，告奸奖赏当场兑现。</p><h3>一年后</h3><p>杜县告书骤增，借粮、留宿和陌生亲戚都可能变成指认。韩甲终于取得陈家争议土地；不久，他弟弟持被雨打湿的请假木牒归家，三份告书同时递进县衙。他终于明白，这套制度不会永远只指向敌人。县中少有公开争执，家家却等待在被告发以前先告发别人。</p>',
  weak:'<h2>法令失信</h2><p>你只付季良一半赏金；逃兵案中又先释放、后因旧族施压重新拘捕部分住户。韩甲的告奸奖赏也一拖再拖。</p><p>百姓不再认真阅读告示，而是打听县令当日态度。有人相信送礼能免连坐，有人认为与令史交好胜过了解规则。季良看着被风吹破的告示说：“木头搬到了北门，官府的信用却没有跟着搬过来。”</p>',
  snow:'<h2>隐藏结局 · 告书如雪</h2><p>韩甲因找到赵武得到重赏，他对陈家的虚假指认却以“不打击告奸之心”为由被搁置。消息传开，案房很快堆满告书：欠债者告债主，争田者告邻居，兄弟分家互告，商人指认竞争者私藏禁物。</p><h3>一年后</h3><p>官府无力核实，只能按告发数量和身份快速定罪。真正的逃犯学会制造假线索，让邻里互相指认。田伯抱着告书说：“从前百姓不肯说；如今人人都在说，可说得越多，我们越不知道什么是真的。”制度成功制造了信息，却没有建立辨别信息的能力。</p>'
 },
 boundary:'徙木立信、什伍编制、连坐、告奸受赏与匿奸重罚有史料依据；杜县逃兵案及卫成、田伯、赵武、孟媪、韩甲、季良等具体人物与程序为教学化虚构。'
};
Object.assign(V[1],SECOND_FINAL);
introTalk=function(){dialogue(C.opening,()=>unlock([0,1],finish))};
function routeMap(){const metA=S.visited.includes('a'),metB=S.visited.includes('b'),ready=metA&&metB;stage(`<section class="d-map av-route-map"><div class="d-map-title"><small>${C.era} · 专属案卷地图</small><h1>${C.title}</h1><p>依次会见关键人物、进入证物现场，再完成制度裁断。每卷地点与人物均随案件变化。</p></div><div class="d-route"></div><button class="d-place ${metA?'done':''}" style="left:18%;top:62%" onclick="avVisit('a')"><i>1</i><b>${C.scenes[0]}</b><span>会见 ${C.people[0]}</span></button><button class="d-place ${metB?'done':''}" style="left:45%;top:28%" onclick="avVisit('b')"><i>2</i><b>${C.scenes[1]}</b><span>会见 ${C.people[1]}</span></button><button class="d-place ${ready?'':'locked'}" style="left:73%;top:58%" onclick="avVisit('e')"><i>3</i><b>${C.scenes[2]}</b><span>${ready?'研判四件材料':'先完成人物会面'}</span></button><button class="d-place locked" style="left:48%;top:80%"><i>4</i><b>${C.scenes[3]}</b><span>证据完成后开放</span></button><aside class="d-map-log"><b>本卷进度</b><span>人物会面 ${S.visited.length}/2</span><span>物证 ${S.evidence.length}/4</span><span>知识节点 ${S.notes.length}/6</span></aside></section>`)};
window.avVisit=id=>{if(id==='e'){if(!(S.visited.includes('a')&&S.visited.includes('b')))return modal('<h1>前序未完成</h1><p>请先完成两场专属人物会面。</p><button onclick="avClose()">返回地图</button>');return investigate()}const idx=id==='a'?0:1;dialogue([...C.meet[idx],[C.role,'这场会面怎样写入调查札记？',[[`记录其制度理由，同时等待证物核验`,'meet_reason','立场与证据分别审查'],[`因其身份或情感直接接受全部说法`,'meet_status','身份不能替代证明'],[`只做道德评价，不记录历史制度依据`,'meet_moral','历史判断需要时代语境']]]],()=>{if(!S.visited.includes(id))S.visited.push(id);save();routeMap()})};
investigate=function(){stage(`<section class="av-workbench"><header><div><small>${C.era} · ${C.scenes[2]}</small><h1>${C.title}</h1><p>${C.intro[1]}</p></div><b>证据 ${S.evidence.length}/4</b></header><div class="av-columns"><aside><h3>本卷人物</h3>${C.people.map((p,i)=>`<article><b>${p}</b><span>${i<2?'已进入人物会面':'将在案情与裁断中出现'}</span></article>`).join('')}</aside><main><h3>四项调查材料 <small>逐件判断证明边界</small></h3><div class="av-evidence-grid">${C.evidence.map((x,i)=>`<button ${i>S.evidence.length?'disabled':''} class="${i<S.evidence.length?'found':''}" onclick="avEvidence(${i})"><i>${i+1}</i><b>${x[0]}</b><span>${i<S.evidence.length?'已研判 · 可复核':i===S.evidence.length?'点击研判':'前件未完成'}</span></button>`).join('')}</div><div class="av-tip"><b>核心问题</b><p>${C.theme}</p></div></main><aside class="d-lawbox"><h3>证据方法</h3><p>先问材料能证明什么，再问它不能证明什么。真实材料也不能自动包办全案。</p><button onclick="avNotes()">查看法脉札记</button></aside></div></section>`)};
evidence=function(i){if(i>S.evidence.length)return;const e=C.evidence[i];modal(`<small>第 ${i+1}/4 件材料 · ${C.scenes[2]}</small><h1>${e[0]}</h1><p>${e[1]}</p><div class="d-proof"><b>可以支持</b>${e[2]}</div><div class="d-limit"><b>不能直接证明</b>${e[3]}</div><h2>你准备怎样使用？</h2><div class="av-proof"><button onclick="avJudge(${i},'chain')">限定证明范围，并与其他材料互证</button><button onclick="avJudge(${i},'absolute')">把它作为全案决定性依据</button><button onclick="avJudge(${i},'discard')">因为有局限而完全排除</button></div><button onclick="avClose()">暂不收入</button>`)};
window.avJudge=(i,x)=>{if(!S.evidence.includes(i))S.evidence.push(i);S.choices.push(`e${i}_${x}`);save();const e=C.evidence[i];modal(`<small>证据研判反馈</small><h1>${x==='chain'?'证明边界清楚':'这一用法过于绝对'}</h1><p>${x==='chain'?'你保留了材料的证明力，也没有让它超出能够回答的问题。':'材料有局限不等于没有价值，真实材料也不能单独证明全部事实。'}</p><div class="d-proof"><b>本件可证明</b>${e[2]}</div><div class="d-limit"><b>本件不能证明</b>${e[3]}</div><button class="primary" onclick="avContinueEvidence()">收入案卷并继续</button>`)};
confrontTalk=function(){dialogue([[C.role,`现有材料是：${C.evidence.map(x=>x[0]).join('、')}。现在必须让人物主张接受证据检验。`],...C.meet[0].slice(0,1),...C.meet[1].slice(0,1),[C.role,'你怎样组织案件事实？',[[`区分已经证明、相互矛盾和仍待证明的部分`,'factmap','证据链不是材料堆叠'],[`只采用支持预设结论的材料`,'confirm','警惕选择性采证'],[`以人物品行和身份代替事实判断`,'character','身份评价不能替代行为证明']]],[C.role,'事实范围已经划定。下一幕将决定制度怎样回应这些事实。']],finish)};
resolve=function(){const chains=S.choices.filter(x=>/^e\d_chain$/.test(x)).length;if(S.i===1){let id='weak';const all=S.strategy==='all'||S.choices.filter(x=>x==='all').length>=2;const snow=S.strategy==='inform_all'||S.choices.includes('reward_all')||(S.choices.includes('inform_all')&&!S.choices.includes('verify_split'));const good=S.choices.includes('reward_full')&&S.choices.includes('detain_investigate')&&S.strategy==='bounded'&&S.choices.includes('trust')&&S.choices.includes('relation_start')&&S.choices.includes('verify_split')&&S.choices.includes('absence_check')&&S.choices.includes('public_records')&&chains>=2;if(all)id='hard';else if(snow)id='snow';else if(good)id='good';S.ending=id;save();return ending()}const goodChoices=['bounded','reform','separate','review','documents','balance','petition_system','kin_distinguish','review_chain','marriage_layers','facts_first','modern_transition','factmap'];const hardChoices=['same','old','clan','real','ritual','kin_same','keep_confession','highest_bid','confirm_real','all_ritual'];let id='weak';if(hardChoices.some(x=>S.choices.includes(x))||['same','old','clan','real','ritual'].includes(S.strategy))id='hard';if(chains>=2&&(goodChoices.some(x=>S.choices.includes(x))||goodChoices.includes(S.strategy))&&S.choices.filter(x=>['purpose','graded','feedback','scope','limited','separate','autopsy','review','chain','documents','family','delay','modern','balance','sovereignty','substance','feedback2','acts','rituallegal','forensic','independent','context','twodocs','distinguish','twosides','translate','condition'].includes(x)).length>=2)id='good';S.ending=id;save();ending()};
ending=function(){const d=C.endings[S.ending]||C.endings.weak;stage(`<section class="d-ending av-ending"><div class="d-end-scroll"><small>第${'二三四五六七八'[S.i-1]}卷 · 完整剧情结局</small><h1>${d[0]}</h1><p class="lead">${d[1]}</p><article class="d-story-ending">${C.stories[S.ending]||C.stories.weak}</article><div class="d-tabs"><button class="on" onclick="avEndTab(this,'learn')">结案知识详解</button><button onclick="avEndTab(this,'route')">我的选择轨迹</button><button onclick="avEndTab(this,'boundary')">史实边界</button></div><div id="avEndPanel"></div><div class="d-end-actions"><button class="primary" onclick="avComplete()">归档并返回八案</button><button onclick="avRestart()">重开本卷</button><button onclick="avNotes()">查看法脉札记</button></div></div></section>`);window.avEndTab(document.querySelector('.d-tabs button'),'learn')};
window.avEndTab=(btn,type)=>{document.querySelectorAll('.d-tabs button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');const p=document.getElementById('avEndPanel');if(type==='learn')p.innerHTML=`<h2>本卷知识总结</h2><div class="d-know-grid">${C.notes.map(n=>`<article><b>${n[0]}</b><span>${n[1]}</span></article>`).join('')}</div><p><b>连续法史线索：</b>本卷不是古代法律“越来越现代”的评分，而是观察制度怎样在秩序、身份、伦理、证据、程序与社会变化之间作出回应。</p>`;if(type==='route')p.innerHTML=`<h2>选择轨迹</h2><p>人物会面 ${S.visited.length}/2 · 物证研判 ${S.evidence.length}/4 · 正式审理 ${C.court.length}轮</p><ol>${S.choices.map(x=>`<li>${x}</li>`).join('')}</ol>`;if(type==='boundary')p.innerHTML=`<h2>史实与教学化虚构</h2><p>${C.boundary}</p><p>游戏中的对话、材料组合和模拟程序用于承载真实制度问题，不应被视作史料原文。</p>`};
const oldLoadFinal=load;load=function(i){const x=oldLoadFinal(i),edition=i===1?'second-detailed-v2':'seven-final';if(x.scriptEdition!==edition){const n=fresh(i);n.visited=[];n.scriptEdition=edition;return n}return x};const oldSaveFinal=save;save=function(){S.scriptEdition=S.i===1?'second-detailed-v2':'seven-final';oldSaveFinal()};
window.startCase=i=>i===0?firstVolume(i):start(i);window.avAdvance=advance;window.avIntroTalk=introTalk;window.avEvidence=evidence;window.avContinueEvidence=continueEvidence;window.avConfrontTalk=confrontTalk;window.avStrategy=strategy;window.avCourtTalk=courtTalk;window.avNotes=notes;window.avClose=close;window.avRun=run;window.avNext=next;window.avComplete=complete;window.avExit=exit;window.avRestart=()=>{localStorage.removeItem(key(S.i));S=fresh(S.i);S.visited=[];S.scriptEdition=S.i===1?'second-detailed-v2':'seven-final';shell();run()};
})();
