(function(){
const oldStart=window.startCase;
const K=[
 {t:'子产铸刑书',d:'公元前536年三月，郑国铸刑书，是中国早期公布成文法的重要事件。具体条文并未完整保存，游戏不能把虚构条文当作史实。',src:'《左传·昭公六年》'},
 {t:'礼刑秩序与身份裁量',d:'春秋时期的裁断综合身份、礼制、惯例和具体情势。它具有灵活性，却也使普通人难以预知刑罚、质疑临事加刑。',src:'春秋晚期礼刑秩序'},
 {t:'叔向的礼治忧虑',d:'叔向担心百姓“征于书”而争讼，粗疏条文、侥幸解释和贿赂会破坏礼治。他不是简单反对一切规范。',src:'叔向遗子产书'},
 {t:'公开不等于现代法治',d:'刑书公开提高规则的可知性，但身份差等、官吏解释权和政治权力依然存在，不能直接等同罪刑法定或法律面前人人平等。',src:'古今制度比较'},
 {t:'证据的证明边界',d:'旧案、验伤、刑鼎拓文和争讼记录各自只能证明部分事实。真实材料也不能自动证明主观动机或案件全貌。',src:'石生案教学模拟'},
 {t:'新法、旧案与越权审查',d:'应区分“用新法直接重判旧案”和“审查原裁断是否无据加刑”。纠正越权不必以新法当然追溯为前提。',src:'石生案模拟廷议'},
 {t:'规则解释与救济',d:'公开文字只是起点。若不记录解释理由、不允许质疑越权，刑书仍可能成为单向威慑百姓的工具。',src:'本卷制度总结'}
];
const places=[
 {id:'gate',n:'郑国城门',x:15,y:62,sub:'听闻百姓争讼'},
 {id:'hall',n:'执政厅',x:44,y:25,sub:'拜见子产'},
 {id:'forge',n:'司寇案房',x:72,y:59,sub:'研判石生案'},
 {id:'court',n:'廷议大堂',x:49,y:78,sub:'完成模拟法庭'}
];
const evidence={mold:['石生旧案','原判服役三月；石生当庭质问游章后，被以“慢上无礼”追加黥刑，卷中未载具体依据。','证明处罚发生变化且加刑依据缺失，不能单独证明游章必然出于报复，也不能证明石生完全无罪。'],rubbing:['刑鼎拓文','拟公布的争界、伤害规范中，没有“质问大夫即处黥刑”的明确条目。','证明新刑书尝试公开部分罪刑标准，不能证明新法当然适用于已经处理的旧案。'],seal:['医者验伤简','游氏家臣仅手臂擦伤；石生受讯后却有明显杖伤。','证明伤害结果可能被夸大并提示讯问用刑，不能证明石生从未推搡，也不能直接证明是谁下令。'],watch:['市井争讼簿','铸刑书消息传出后，援引条文要求解释和重审的人明显增加。','支持叔向关于争讼增加的部分担忧，但不能证明争讼增加必然导致混乱。']};
const dialogues={
 gate:[['石生','旧族大夫临事加刑，案卷上却没有百姓事先能知道的标准。若刑书落鼎，我的旧案能重审吗？'],['沈衡','刑书公开首先改变什么？',[['百姓能够预知并援引罪刑规则。','public','知识节点：法律公开与可预期性'],['只让刑罚显得更有威严。','fear','知识节点：公开若只有威慑，仍可能是单向治理'],['贵族仍可临时决定，不必公开。','secret','知识节点：秘密刑与身份裁量']]]],
 hall:[['子产','郑国争讼日多，旧礼已不能处理所有变化。我欲铸刑书，使民知所避。'],['叔向来书','民知有辟，则不忌于上，并有争心，以征于书，而侥幸以成之。'],['子产','你如何理解叔向的反对？',[['他维护礼治与身份秩序，也担心粗疏条文引发争讼。','understand','知识节点：礼治反对意见的历史语境'],['他只是害怕百姓识字，不必回应。','dismiss','知识节点：不能把历史争论简化为守旧'],['他说得完全正确，应停止铸鼎。','stop','知识节点：礼治秩序与规则公开的冲突']]]]
};
let S,Q=[],active=null;
function base(){return{v:3,student:'',phase:'guide',visited:[],choices:[],evidence:[],knowledge:[],court:0,ending:null,questions:[],savedAt:null}}
function load(){try{return Object.assign(base(),JSON.parse(localStorage.getItem('ding-teach-v3')||'{}'))}catch(e){return base()}}
function save(){S.savedAt=Date.now();localStorage.setItem('ding-teach-v3',JSON.stringify(S));const e=document.getElementById('dSave');if(e){e.textContent='已自动存档';setTimeout(()=>e.textContent='自动存档开启',900)}}
function shell(){document.getElementById('dingGame')?.remove();const e=document.createElement('section');e.id='dingGame';e.innerHTML=`<div class="d-bg"></div><header class="d-top"><button class="d-brand" onclick="dMap()"><small>第一卷 · 春秋郑国</small><b>鼎火照夜</b></button><div><span id="dSave">自动存档开启</span><button onclick="dProfile()">学习档案</button><button class="d-ai-btn" onclick="dAI()">AI 法史司业</button><button onclick="dExit()">八案地图</button></div></header><main id="dMain"></main><div id="dChar" class="d-char p0"></div><section id="dDialogue" class="d-dialog hidden"><strong id="dSpeaker"></strong><p id="dText"></p><div id="dChoices"></div><button id="dNext" onclick="dNext()">点击继续 ▾</button></section><div id="dModal" class="d-modal hidden"></div>`;document.body.appendChild(e)}
function start(){S=load();shell();if(S.savedAt&&S.phase!=='guide'&&S.phase!=='done')resume();else guide()}
function resume(){modal(`<small>发现学习存档</small><h1>继续《鼎火照夜》？</h1><p>${S.student||'未命名学员'} · 已完成 ${S.visited.length}/4 个场景 · 已研判 ${S.evidence.length}/4 件材料</p><button class="primary" onclick="dResume()">继续学习</button><button onclick="dRestart()">重新开始</button>`)}
function guide(){S.phase='guide';main(`<section class="d-guide"><div class="d-scroll"><small>案前导学卷</small><h1>鼎火照夜</h1><p class="lead">公元前536年，郑国子产命人把刑书铸在鼎上。规则第一次走出贵族官署，被普通国人看见。可在落鼎前夜，一行约束官吏越制的文字被人削去了。</p><div class="d-guide-grid"><article><b>时代坐标</b><span>春秋后期 · 郑国</span></article><article><b>对应章节</b><span>成文法公布与礼法冲突</span></article><article><b>核心问题</b><span>谁能知道、解释并援引规则？</span></article><article><b>你的身份</b><span>司寇属吏 · 沈衡</span></article></div><h2>本卷学习目标</h2><ol><li>解释子产铸刑书的法制史意义</li><li>理解叔向反对意见的礼治语境</li><li>区分法律公开与现代法治</li><li>运用证据处理旧案与官吏越权</li></ol><label>学习档案姓名或学号<input id="dStudent" value="${S.student}" placeholder="例如：法学2301-张同学"></label><button class="primary" onclick="dBegin()">署名入卷</button></div></section>`)}
function begin(){S.student=document.getElementById('dStudent').value.trim()||'匿名学员';S.phase='map';learn(0);save();map()}
function map(){S.phase='map';hideDialog();document.getElementById('dChar').classList.add('hidden');main(`<section class="d-map"><div class="d-map-title"><small>郑国 · 案卷行旅图</small><h1>一夜四处，鼎火将明</h1><p>先在城门受理阿荇申诉，再赴执政厅研读叔向来书；随后进入司寇案房研判材料，最后参加廷议。</p></div><div class="d-route"></div>${places.map((p,i)=>{const locked=(p.id==='forge'&&(!S.visited.includes('gate')||!S.visited.includes('hall')))||(p.id==='court'&&S.evidence.length<3);return `<button class="d-place ${S.visited.includes(p.id)?'done':''} ${locked?'locked':''}" style="left:${p.x}%;top:${p.y}%" onclick="dVisit('${p.id}')"><i>${i+1}</i><b>${p.n}</b><span>${locked?'前序未完成':p.sub}</span></button>`}).join('')}<aside class="d-map-log"><b>本卷进度</b><span>人物会面 ${S.visited.filter(x=>x==='gate'||x==='hall').length}/2</span><span>材料 ${S.evidence.length}/4</span><span>知识节点 ${S.knowledge.length}/${K.length}</span></aside></section>`);save()}
function visit(id){if(id==='forge'&&(!S.visited.includes('gate')||!S.visited.includes('hall')))return toast('先完成城门与执政厅的人物会面。');if(id==='court'&&S.evidence.length<3)return toast('至少收集三件物证后才能开庭。');if(!S.visited.includes(id))S.visited.push(id);active=id;save();if(dialogues[id])talk(dialogues[id],id);else if(id==='forge')forge();else court()}
function talk(lines,id){document.getElementById('dChar').className=`d-char p${id==='gate'?2:0}`;main(`<section class="d-scene"><aside><small>${id==='gate'?'城门申诉处':'执政厅'}</small><h1>${id==='gate'?'石生旧案':'铸刑之议'}</h1><p>${id==='gate'?'听取平民为何要求公开刑书。':'面对子产与叔向跨越国界的礼法争论。'}</p></aside></section>`);Q=lines.slice();nextLine()}
function nextLine(){if(!Q.length){hideDialog();if(active==='gate')learn(1);if(active==='hall'){learn(2);learn(3)}save();return map()}const x=Q.shift(),d=document.getElementById('dDialogue');d.classList.remove('hidden');document.getElementById('dSpeaker').textContent=x[0];document.getElementById('dText').textContent=x[1];const c=document.getElementById('dChoices');c.innerHTML='';document.getElementById('dNext').hidden=!!x[2];if(x[2])x[2].forEach((o,i)=>{const b=document.createElement('button');b.innerHTML=`<i>${String.fromCharCode(65+i)}</i>${o[0]}<small>${o[2]}</small>`;b.onclick=()=>{S.choices.push(o[1]);save();nextLine()};c.appendChild(b)})}
function forge(){S.phase='forge';document.getElementById('dChar').className='d-char p1';main(`<section class="d-forge"><div class="d-scene-card"><small>铸鼎工坊 · 场景调查</small><h1>鼎文被改</h1><p>点击发光调查点。每件物证都包含“能证明什么”与“不能证明什么”。</p></div><div class="d-hot h1" onclick="dEvidence('mold')"><i>查</i><b>泥范</b></div><div class="d-hot h2" onclick="dEvidence('rubbing')"><i>拓</i><b>拓印案</b></div><div class="d-hot h3" onclick="dEvidence('seal')"><i>验</i><b>麻布私印</b></div><div class="d-hot h4" onclick="dEvidence('watch')"><i>核</i><b>值夜簿</b></div><div class="d-tray">${Object.keys(evidence).map(k=>`<span class="${S.evidence.includes(k)?'on':''}">${S.evidence.includes(k)?evidence[k][0]:'未发现'}</span>`).join('')}<button onclick="dMap()">返回地图</button></div></section>`)}
function inspect(k){const e=evidence[k];if(!S.evidence.includes(k))S.evidence.push(k);if(k==='rubbing')learn(4);save();modal(`<small>物证特写</small><h1>${e[0]}</h1><p>${e[1]}</p><div class="d-proof"><b>可以支持</b>${e[2].split('，')[0]}。</div><div class="d-limit"><b>证明边界</b>${e[2]}</div><button class="primary" onclick="dCloseForge()">收入案卷</button>`)}
function court(){S.phase='court';document.getElementById('dChar').className='d-char p3';main(`<section class="d-court"><div class="d-bench"><small>模拟法庭 · 执政厅廷议</small><h1>刑书应当约束谁？</h1><p id="dCourtPrompt"></p><div id="dCourtOptions"></div></div><aside class="d-evidence-bar"><b>已呈物证</b>${S.evidence.map(k=>`<span>${evidence[k][0]}</span>`).join('')}</aside></section>`);courtStep()}
const courtQs=[
 ['游氏大夫称刑书只能教民畏法，不能让百姓质问官吏。你如何回应？',[['公开规则也应说明执法者权限，越制官吏须受约束。','bind'],['只公开百姓不得做什么，官吏仍可临时决定。','oneway'],['公开文字已经足够，不必设置申诉。','symbol']]],
 ['石生旧案发生在刑书公布前。怎样处理才不等于简单追溯新法？',[['先审查原案是否改卷、越权加刑，再决定救济。','procedure'],['所有旧案一律依新刑书重判。','retro'],['封存旧案，避免争讼。','bury']]],
 ['刑书落鼎后，如何处理解释与申诉？',[['全文公布、保存解释簿，并允许控告越权适用。','complete'],['只公布刑名，解释仍留官署。','limited'],['停止铸鼎，恢复临事议制。','stop']]]
];
function courtStep(){if(S.court>=courtQs.length)return resolve();const q=courtQs[S.court];document.getElementById('dCourtPrompt').textContent=`第 ${S.court+1}/3 轮：${q[0]}`;document.getElementById('dCourtOptions').innerHTML=q[1].map((o,i)=>`<button onclick="dCourtChoose('${o[1]}')"><i>${String.fromCharCode(65+i)}</i>${o[0]}</button>`).join('')}
function courtChoose(x){S.choices.push(x);S.court++;save();if(S.court===1)learn(4);if(S.court===2)learn(5);courtStep()}
function resolve(){let id='mixed';if(S.choices.includes('complete')&&S.choices.includes('procedure')&&S.choices.includes('fact_bounded'))id='light';else if(S.choices.includes('stop')||S.choices.includes('stop_early'))id='noDing';else if(S.choices.includes('oneway')||S.choices.includes('rank_first'))id='power';else if(S.choices.includes('limited'))id='shadow';else if(S.choices.includes('retro'))id='storm';learn(6);S.ending=id;S.phase='done';save();ending()}
const ENDINGS={
 light:{title:'鼎铭留世',summary:'你区分了石生的基础责任与游章的越权加刑，也没有让新刑书简单追溯旧案。刑书落鼎之时，解释记录与有限申诉一并建立。',story:`<h2>终局故事</h2><p>铜水灌入鼎范的同时，司寇府宣读石生案的最终裁断：石生推人伤人，仍服原定三月劳役；游章仅因其当庭质问便追加黥刑，案无所据，撤销黥刑，并责令将加刑理由写入案卷。</p><p>阿荇没有等到兄长被宣布“完全无罪”，却看见黥针被收回。石生临行前望着刑鼎说：“我愿为推人服役，只愿以后有人加刑时，不能只说一句你不敬我。”</p><h3>一个月后</h3><p>刑鼎立在城南，援引文字申诉的人果然增加。有人误解条文，也有人向书吏求取有利解释。史墨把每次适用和争议记入解释簿：“叔向并未全错。可从前没有争论，难道就没有冤屈？”</p><h3>三个月后</h3><p>石生服役归来，重新开起修补农具的小铺。游章仍是大夫，但每当准备改变处罚时，司寇府都会递上一片空白竹简：“请写明依据。”刑鼎没有消灭身份差等，却让权力第一次在部分案件中需要说明理由。</p>`},
 power:{title:'鼎为威器',summary:'刑书公开了，却主要用来威慑百姓。石生的黥刑得到维持，贵族与官吏仍可依身份另行裁断。',story:`<h2>终局故事</h2><p>刑鼎铸成当日，石生被押到城南。阿荇指着鼎文追问：“家兄的黥刑依据写在哪里？”游章没有回答，只说刑书是让百姓知所畏惧，不是让他们质问大夫。</p><p>黥针刺入石生额角。新铸刑鼎在日光下清晰可见，百姓第一次看见罪刑文字，却也第一次明白，那些文字未必同样约束作出裁断的人。</p><h3>一个月后</h3><p>盗窃和街市斗殴有所减少，申诉也越来越少。史墨告诉你：“他们知道鼎文能证明自己犯了什么，却不能证明官吏越过了什么。”</p><h3>半年后</h3><p>石生服役归来，因黥印失去原来的生意，只能在城外修补车轮。一个孩子指着刑鼎问父亲：“这些规则也约束大夫吗？”父亲立刻捂住他的嘴。文字已经公开，权力边界依旧隐藏。</p>`},
 noDing:{title:'鼎火熄灭',summary:'你选择停止铸鼎，避免条文争议并保留礼治裁断的灵活性。石生案被送回旧族，刑罚标准重新回到普通人无法预知的裁量中。',story:`<h2>终局故事</h2><p>尚未冷却的铜水被倒回炉中，刻好文字的泥范被铁锤砸碎。阿荇从泥土中捡起一片残范，上面只剩半个无法辨认的“刑”字。</p><p>石生案被退回游章处理。数日后，结案简上只有八个字：“慢上伤人，依礼处置。”没有人说明“依礼”对应什么标准，黥刑如期执行。</p><h3>一个月后</h3><p>城南恢复平静。没有人围绕条文争论，官员也能根据身份和情势灵活裁断。但同样的争界伤人，贵族家臣赔偿财物，普通农人却可能服役受刑。</p><h3>一年后</h3><p>史墨在旧案库找出石生残卷：“争讼确实少了，不是因为人人信服，而是因为他们不知道依据什么争，也不知道争了是否有人会听。”没有公开规则，未必没有刑罚；没有争讼，也未必没有冤屈。</p>`},
 shadow:{title:'字在鼎上，权在吏中',summary:'你完成了文字公开，却没有公开解释过程或建立救济。刑书的含义逐渐被少数官吏垄断。',story:`<h2>隐藏结局</h2><p>刑鼎立起之初，百姓以为同样的文字会带来同样的裁断。很快，人们发现“伤人”“扰乱”等词仍要由书吏解释。</p><h3>三个月后</h3><p>同样是争界推搡，送给书吏一匹布的人被解释为“无意相触”，无钱送礼的人被认定为“怀怒伤人”。他们都指着同一座刑鼎辩护，书吏却说：“鼎上只有文字，如何适用，自然由我们判断。”</p><h3>一年后</h3><p>石生站在鼎下说：“我曾以为文字在那里，人人便会得到同样裁断。现在才知道，文字不会自己说话。”过去规则藏在贵族心中，如今文字虽然公开，解释权却藏进官吏袖中。</p>`},
 storm:{title:'争端满城',summary:'你让新刑书全面追溯旧案。部分旧日不公被揭开，但证据散失、规范冲突和选择性重审使郑国陷入新的混乱。',story:`<h2>终局故事</h2><p>石生因新刑书中没有对应的黥刑条目而获释。消息传开，数百宗旧案同时要求重判。有人因新规则减轻处罚，也有人被官吏按照新规则追加责任。</p><h3>数月后</h3><p>旧证人死亡、案卷残缺、旧规范与新文字互相冲突。百姓争问为何有的旧案重审、有的封存。你救下了石生，却没能说明新法追溯的统一边界。郑国终于明白：结果看似正义，不代表适用方法已经稳定。</p>`},
 mixed:{title:'鼎火未明',summary:'刑书已经铸成，但石生责任、官吏解释和旧案救济没有形成一致安排。制度仍在文字公开与身份裁量之间摇摆。',story:`<h2>终局故事</h2><p>石生的黥刑被暂缓，刑鼎也在争议中落成。司寇府没有明确新法能否处理旧案，也没有决定解释是否必须记录。</p><p>几个月后，同类案件出现不同裁断。人们既开始引用刑书，也继续依赖贵族的临事决定。鼎火照亮了文字，却没有照清文字如何进入案件。你的案卷没有结束，只被留给下一次争论。</p>`}
};
function ending(){const d=ENDINGS[S.ending]||ENDINGS.mixed;document.getElementById('dChar').classList.add('hidden');main(`<section class="d-ending"><div class="d-end-scroll"><small>第一卷剧情结局</small><h1>${d.title}</h1><p class="lead">${d.summary}</p><article class="d-story-ending">${d.story}</article><div class="d-tabs"><button class="on" onclick="dEndTab(this,'history')">结案知识详解</button><button onclick="dEndTab(this,'evidence')">证据教学</button><button onclick="dEndTab(this,'route')">选择轨迹</button><button onclick="dEndTab(this,'boundary')">史实边界</button></div><div id="dEndPanel"></div><div class="d-end-actions"><button class="primary" onclick="dProfile()">收入学习档案</button><button onclick="dRestart()">重开本卷</button><button onclick="dExit()">归档并返回八案</button></div></div></section>`);endTab(document.querySelector('.d-tabs button'),'history')}
function endTab(btn,type){document.querySelectorAll('.d-tabs button').forEach(x=>x.classList.remove('on'));btn.classList.add('on');const p=document.getElementById('dEndPanel');if(type==='history')p.innerHTML=`<h2>结案知识页</h2><h3>1. 为什么要铸刑书？</h3><p>公元前536年，春秋晚期的郑国面临田界重分、社会关系变化和争讼增加。旧有裁断综合礼制、身份、惯例与具体情势，虽有灵活性，却使普通人难以事先知道处罚标准。刑书公布，使部分罪刑规范从贵族和官府掌握的知识转为国人可以看见的规则。</p><h3>2. 叔向为什么反对？</h3><p>叔向担心百姓“征于书”而争讼，并忧虑条文粗疏、侥幸解释和贿赂破坏礼治。他不是主张国家完全不要刑罚，而是反对用公开、固定的刑书取代礼义教化和贤明者的临事裁断。其忧虑有现实一面，但也会使普通人缺乏质疑身份裁量的公开依据。</p><h3>3. 子产如何回应？</h3><p>子产的答复强调自己无力谋及子孙，只求“救世”，表现出改革的现实主义：刑书并非永远完美的答案，而是旧有治理方式难以回应当下社会变化时的制度选择。</p><h3>4. 为什么不等于现代法治？</h3><p>刑书公开提高了规则可知性，却没有自动建立法律面前人人平等、司法独立、正当程序、稳定解释和权利救济。身份差等与政治权力仍然存在。准确表述应是：它是中国早期成文法公布的重要事件，而非现代法治的完成。</p><div class="d-know-grid">${K.map(k=>`<article><b>${k.t}</b><span>${k.d}</span><small>${k.src}</small></article>`).join('')}</div>`;if(type==='evidence')p.innerHTML=`<h2>证据为什么有边界？</h2><p><b>石生旧案</b>能证明处罚发生变化、加刑依据未载，不能直接证明石生完全无罪或游章必然报复。</p><p><b>刑鼎拓文</b>能证明拟公开规则中没有对应黥刑，不能证明尚未公布的新法当然追溯旧案。</p><p><b>医者验伤简</b>能说明伤势较轻并提示讯问用刑，不能否认石生曾推搡，也不能直接证明下令者。</p><p><b>市井争讼簿</b>能支持争讼增加这一现象，不能证明争讼增加必然是坏事；它也可能意味着旧有不满获得表达渠道。</p><p><b>教学结论：</b>一件材料“能支持什么”和“不能证明什么”同样重要。应以多项材料互证，避免让单一证据包办全案。</p>`;if(type==='route')p.innerHTML=`<h2>你的学习轨迹</h2><p>完成场景：${S.visited.length}/4　案件材料：${S.evidence.length}/4　知识节点：${S.knowledge.length}/${K.length}</p><ol>${S.choices.map(x=>`<li>${x}</li>`).join('')}</ol>`;if(type==='boundary')p.innerHTML='<h2>史实与教学化虚构</h2><h3>有史料依据</h3><p>公元前536年郑国铸刑书；叔向来书反对，担心百姓征引刑书争讼；子产以解决当下危局回应。核心记载见《左传·昭公六年》。</p><h3>教学化虚构</h3><p>石生、阿荇、游章、史墨及争界推搡案，旧案、验伤简、争讼簿和具体申诉程序均为游戏设计。由于子产刑书的具体条文没有完整保存，游戏不会把拟制条文当作真实法典原文。</p><h3>为什么虚构？</h3><p>史料保存的是重大政治事件与思想争论，缺少一宗可完整互动的普通人案件。本卷用虚构案件承载真实制度问题：法律为何公开、是否约束掌权者、新法能否处理旧案、证据怎样互证，以及解释权如何受到限制。</p>'}
function ai(){modal(`<section class="d-ai"><small>案例知识库问答</small><h1>AI 法史司业</h1><p>回答只依据本卷知识库，并明确显示依据。</p><div class="d-ai-quick">${['为什么叔向反对铸刑书？','铸刑书等于现代法治吗？','石生旧案为什么不能直接用新法？','刑书公开后谁来解释？'].map(q=>`<button onclick="dAsk('${q}')">${q}</button>`).join('')}</div><label>也可以输入问题<input id="dAIInput" placeholder="输入与本案有关的问题"></label><button class="primary" onclick="dAskInput()">向司业提问</button><div id="dAIAnswer"></div><button onclick="dClose()">返回案件</button></section>`)}
function ask(q){const rules=[[/叔向|反对/,2],[/现代|法治|罪刑法定/,3],[/旧案|新法|追溯/,5],[/解释|官吏|约束/,6],[/证据|证明/,4],[/公开|意义/,0]];const hit=rules.find(x=>x[0].test(q)),k=K[hit?hit[1]:0];S.questions.push(q);save();document.getElementById('dAIAnswer').innerHTML=`<b>简明回答</b><p>${k.d}</p><b>本案依据</b><p>${k.src}</p><b>古今边界</b><p>${hit&&hit[1]===3?'可以比较规则公开的价值，但不能把先秦制度直接称为现代法治。':'应先按春秋时期的礼刑秩序理解，再与现代制度比较。'}</p>`}
function profile(){modal(`<small>个人学习档案</small><h1>${S.student||'匿名学员'}</h1><div class="d-profile"><article><b>${S.visited.length}/4</b><span>场景完成</span></article><article><b>${S.evidence.length}/4</b><span>材料研判</span></article><article><b>${S.knowledge.length}/${K.length}</b><span>知识节点</span></article><article><b>${S.questions.length}</b><span>AI提问</span></article></div><h2>已掌握</h2><p>${S.knowledge.length?S.knowledge.map(i=>K[i].t).join(' · '):'尚未开始学习'}</p><button onclick="dClose()">关闭档案</button>`)}
function learn(i){if(!S.knowledge.includes(i))S.knowledge.push(i)}function main(h){document.getElementById('dMain').innerHTML=h}function modal(h){const m=document.getElementById('dModal');m.classList.remove('hidden');m.innerHTML=`<div>${h}</div>`}function close(){document.getElementById('dModal').classList.add('hidden')}function hideDialog(){document.getElementById('dDialogue').classList.add('hidden')}function toast(x){modal(`<h2>${x}</h2><button onclick="dClose()">知道了</button>`)}
window.startCase=i=>i===0?start():oldStart(i);window.dBegin=begin;window.dMap=map;window.dVisit=visit;window.dNext=nextLine;window.dEvidence=inspect;window.dCloseForge=()=>{close();forge()};window.dCourtChoose=courtChoose;window.dEndTab=endTab;window.dAI=ai;window.dAsk=ask;window.dAskInput=()=>ask(document.getElementById('dAIInput').value||'铸刑书的意义是什么？');window.dProfile=profile;window.dClose=close;window.dResume=()=>{close();S.phase==='forge'?forge():S.phase==='court'?court():S.phase==='done'?ending():map()};window.dRestart=()=>{localStorage.removeItem('ding-teach-v3');S=base();shell();guide()};window.dExit=()=>{save();document.getElementById('dingGame')?.remove();window.openMap()};
guide=function(){S.phase='guide';document.getElementById('dChar').classList.add('hidden');main(`<section class="d-platform"><nav class="d-side"><h2>律令山河录</h2><button class="on">⌂ 时代总览</button><button>◈ 历史时间轴</button><button>◉ 人物对话</button><button>▣ 案例模拟</button><button>◇ 物证探索</button><button onclick="dProfile()">◎ 学习档案</button></nav><div class="d-platform-main"><header><small>中国法制史 · 沉浸式学习平台</small><h1>从礼刑秩序走向成文法公开</h1></header><div class="d-era-line">${['先秦','秦汉','魏晋隋唐','宋元','明清','近现代'].map((x,i)=>`<span class="${i===0?'on':''}"><i></i>${x}</span>`).join('')}</div><section class="d-overview"><div><small>第一卷 · 公元前536年 · 郑国</small><h2>鼎火照夜</h2><p>田界重分、争讼渐多，子产准备把刑书铸在鼎上。落鼎前夕，平民阿荇携兄长石生的旧案在鼎下喊冤：原定三月劳役，为何只因质问大夫便追加黥刑？你将以司寇属吏沈衡的身份调查案件，在礼治、公开规则与旧案救济之间作出裁断。</p></div><aside><b>本卷学习目标</b><span>理解子产铸刑书的时代背景</span><span>辨析叔向的礼治忧虑</span><span>区分证据证明力与证明边界</span><span>处理新法、旧案与越权加刑</span></aside></section><div class="d-module-grid"><article><i>简</i><b>通史导入</b><span>春秋晚期社会变化</span></article><article><i>鼎</i><b>律典研读</b><span>子产与叔向的史料争论</span></article><article><i>案</i><b>案例模拟</b><span>重审石生加刑案</span></article><article><i>人</i><b>人物对话</b><span>子产、叔向、阿荇与石生</span></article><article><i>证</i><b>物证探索</b><span>研判四件案件材料</span></article><article><i>卷</i><b>学习档案</b><span>保存轨迹与知识节点</span></article></div><footer class="d-enter"><label>学习档案姓名或学号<input id="dStudent" value="${S.student}" placeholder="例如：法学2301-张同学"></label><button class="primary" onclick="dBegin()">进入第一卷</button></footer></div></section>`)};
forge=function(){S.phase='forge';document.getElementById('dChar').className='d-char hidden';main(`<section class="d-caseboard"><header><button onclick="dMap()">‹ 返回郑国地图</button><div><small>案例模拟 · 司寇案房</small><h1>石生越权加刑案</h1></div><b>调查进度 ${S.evidence.length}/4</b></header><div class="d-case-progress">${['案情了解','证据收集','制度辨析','廷议辩论','判决裁定'].map((x,i)=>`<span class="${i<2?'on':''}"><i>${i+1}</i>${x}</span>`).join('')}</div><div class="d-case-columns"><aside class="d-roles"><h3>案中人物</h3><article class="on"><b>沈衡</b><span>司寇属吏 · 你的角色</span></article><article><b>石生</b><span>因争界推搡被追加黥刑</span></article><article><b>阿荇</b><span>携残卷为兄申诉</span></article><article><b>游章</b><span>主张依礼维护尊卑</span></article></aside><main class="d-file"><section class="d-file-intro"><div><small>案件背景</small><h2>一句质问，何以追加黥刑？</h2><p>石生推搡游氏家臣，原议服役三月；当庭质问游章后，却被以“慢上无礼”追加黥刑。刑书尚未正式公布，你需要判断原案事实、加刑依据以及新规则能否处理旧案。</p></div><b>核心争点<br><em>新法不追溯，能否审查旧案越权？</em></b></section><h3>案件材料 <small>点击判断“能证明”与“不能证明”</small></h3><div class="d-evidence-grid">${Object.keys(evidence).map((k,i)=>`<button class="${S.evidence.includes(k)?'found':''}" onclick="dEvidence('${k}')"><i>${['卷','鼎','验','簿'][i]}</i><b>${evidence[k][0]}</b><span>${S.evidence.includes(k)?'已研判 · 点击复核':'待调查'}</span></button>`).join('')}</div><section class="d-dispute"><h3>调查提示</h3><p>真实材料也有证明边界：旧案未载依据，不等于石生完全无罪；验伤较轻，也不能否认推搡行为。请避免让一件材料包办全案。</p></section></main><aside class="d-lawbox"><h3>法制史依据</h3><article><b>《左传·昭公六年》</b><span>“三月，郑人铸刑书。”叔向随后来书反对。</span></article><article><b>制度争点</b><span>规则公开、身份裁量、旧案救济、解释权与争讼。</span></article><article><b>史实边界</b><span>铸刑书与叔向来书有史料依据；石生案及具体程序为教学化虚构。</span></article><button onclick="dAI()">询问 AI 法史司业</button></aside></div><footer class="d-case-next"><span>已研判 ${S.evidence.length} 件材料；至少三件后可进入廷议。</span><button onclick="dMap()">保存并返回地图</button></footer></section>`)};
court=function(){S.phase='court';document.getElementById('dChar').className='d-char hidden';main(`<section class="d-caseboard d-trialboard"><header><button onclick="dMap()">‹ 返回郑国地图</button><div><small>模拟法庭 · 执政厅廷议</small><h1>刑书应当约束谁？</h1></div><b>廷议第 ${Math.min(S.court+1,3)} 轮</b></header><div class="d-case-progress">${['案情了解','证据收集','法条援引','廷议辩论','判决裁定'].map((x,i)=>`<span class="${i<=3?'on':''}"><i>${i+1}</i>${x}</span>`).join('')}</div><div class="d-trial-grid"><aside class="d-present"><h3>已呈物证</h3>${S.evidence.map(k=>`<span>${evidence[k][0]}</span>`).join('')||'<p>尚未收集物证</p>'}<h3>本轮法史焦点</h3><p>选择不仅改变结局，也代表你对法律公开、官吏约束与新法适用的立场。</p></aside><main class="d-bench"><small>执政子产请你陈述</small><h1>廷议进行中</h1><p id="dCourtPrompt"></p><div id="dCourtOptions"></div></main><aside class="d-lawbox"><h3>援引提示</h3><article><b>礼治立场</b><span>规范因身份与等级而异，反对公开刑书引发争讼。</span></article><article><b>公布成文法</b><span>让民众能够知晓并援引规则，但不等同现代法治。</span></article><article><b>证据原则</b><span>区分物证的证明对象、来源和证明力。</span></article></aside></div></section>`);courtStep()};
dialogues.gate=[['阿荇','民女阿荇，请司寇府重审家兄石生之案！他原判服役三月，只因当堂问游章“加刑依据何在”，便被追加黥刑。'],['游氏家臣','平民质问大夫，便是慢上无礼。大夫依礼加刑，有何不可？'],['沈衡','你是否受理这份申诉？',[['受理，先查原判为何改变、追加黥刑依据何在。','gate_records','开启：规则依据与越权审查'],['暂缓，等刑书公布后再讨论旧案。','gate_wait','开启：新法是否追溯旧案'],['拒绝，大夫依身份临事裁断即可。','gate_rank','开启：礼治身份裁量路线']]],['石生','我推过人，愿服原定之役。我只问：一句质问，为何要在脸上留下一生的刑印？'],['守门卒','若人人拿着刑书来争，官府岂不日日被围？叔向的担忧，或许就会成真。'],['沈衡','刑书公开首先可能改变什么？',[['百姓能预知部分罪刑，也能询问裁断为何偏离公开规则。','public','知识节点：法律公开与可预期性'],['只是把刑罚写得更威严，不必限制官吏。','fear','知识节点：单向公开可能成为威慑工具'],['争讼会增加，所以规则最好继续保密。','secret','知识节点：无争讼不等于无冤屈']]],['阿荇','鼎上的文字若只能告诉百姓不可做什么，却不能问大夫为何加刑，那它究竟照亮了谁？']];
dialogues.hall=[['子产','田界重分、商旅渐盛，郑国争讼日多。旧礼并非全无规则，却难以处理所有新争。我欲铸刑书，使民知所避。'],['叔向来书','民知有辟，则不忌于上，并有争心，以征于书，而侥幸以成之。'],['沈衡','你如何理解叔向的反对？',[['他维护礼治与身份秩序，也担心条文粗疏、争讼和贿赂。','understand','知识节点：叔向不是简单反对一切法律'],['他只是害怕百姓识字，不必回应。','dismiss','知识节点：不要把历史争论简化为先进与落后'],['既有风险，就应永远停止公布规则。','stop_early','知识节点：礼治灵活性与秘密裁量的代价']]],['子产','若吾子之言，侨不才，不能及子孙，吾以救世也。我并非不知刑书有弊，只是今日之郑国，已不能只靠旧礼断新争。'],['史墨','刑书文字简略。百姓纵能看见，仍要有人解释；解释若不留记录，权力只是从贵族心中移到书吏袖中。'],['沈衡','铸刑书是否等于现代法治已经建立？',[['不是。它推进规则公开，但身份差等、权力制约和平等适用仍未建立。','boundary','知识节点：成文法公开不等于现代法治'],['是。只要出现成文法，古今制度便完全相同。','modernize','知识节点：避免现代概念直接套用先秦'],['不是，所以铸刑书没有任何历史意义。','deny_value','知识节点：既辨析局限，也承认历史变化']]],['子产','去查石生旧案。回来告诉我：不用新法直接追溯，能否仍然审查原审越权？刑书落鼎后，解释与申诉又应如何安排？']];
courtQs.splice(0,courtQs.length,
 ['石生确曾推搡游氏家臣，但伤势轻微。你如何认定基础责任？',[['承认推搡责任，继续审查追加黥刑是否有据。','fact_bounded'],['因追加黥刑可疑，直接宣布石生从未违法。','erase_all'],['只看石生身份卑微，不再审查伤势与行为。','rank_first']]],
 ['四件材料应当怎样共同使用？',[['分别说明证明力与局限，再以旧案、验伤及其他材料互证。','corroborate'],['旧案没有写依据，一件材料就足以证明全部事实。','singleproof'],['材料都有局限，所以全部排除，只听大夫判断。','ignoreproof']]],
 ['石生旧案发生在刑书公布前，怎样处理才不等于简单追溯新法？',[['不直接以新法宣告无罪，先审查原案是否无据加刑、越权裁断。','procedure'],['凡旧案一律依新刑书重新判决。','retro'],['只要发生在刑书前，就永远不得审查。','bury']]],
 ['叔向担忧百姓“征于书”而争讼，你如何回应？',[['承认争讼和解释风险，同时公开解释理由、记录适用并设置有限申诉。','answer_ritual'],['叔向只是守旧，所有担忧都不值得讨论。','mock_ritual'],['为避免争讼，停止铸鼎并恢复临事议制。','stop']]],
 ['请提交最后制度安排。',[['公开主要罪刑、保存解释簿，并允许对越权加刑提出申诉。','complete'],['刑书只用来约束百姓，贵族仍可依身份另行加刑。','oneway'],['文字公开即可，解释仍由官吏秘密掌握且不留记录。','limited']]]
);
courtStep=function(){if(S.court>=courtQs.length)return resolve();const q=courtQs[S.court];const prompt=document.getElementById('dCourtPrompt'),opts=document.getElementById('dCourtOptions');if(!prompt||!opts)return;prompt.textContent=`第 ${S.court+1}/${courtQs.length} 轮：${q[0]}`;opts.innerHTML=q[1].map((o,i)=>`<button onclick="dCourtChoose('${o[1]}')"><i>${String.fromCharCode(65+i)}</i>${o[0]}<small>选择将写入判词轨迹</small></button>`).join('')};
inspect=function(k){const e=evidence[k];modal(`<small>物证研判 · 先判断再收入案卷</small><h1>${e[0]}</h1><p>${e[1]}</p><h2>这件物证目前最合理的证明作用是？</h2><div class="d-proof-choices"><button onclick="dJudgeEvidence('${k}','careful')">作为线索，与其他物证和证言互相印证</button><button onclick="dJudgeEvidence('${k}','absolute')">单独证明游氏就是全部行为的主谋</button><button onclick="dJudgeEvidence('${k}','ignore')">物证不如口供，可以完全排除</button></div><button onclick="dClose()">暂不收入</button>`)};
window.dEvidence=inspect;window.dJudgeEvidence=(k,choice)=>{const e=evidence[k];if(!S.evidence.includes(k))S.evidence.push(k);S.choices.push('evidence_'+k+'_'+choice);if(k==='rubbing')learn(4);save();modal(`<small>研判结果</small><h1>${choice==='careful'?'证据链正在形成':'注意证明边界'}</h1><p>${choice==='careful'?'你的判断较为稳妥：任何单件物证都应放入完整证据链中理解。':'这一判断过于绝对。物证既不能自动证明全部事实，也不应因需要解释就被排除。'}</p><div class="d-proof"><b>可以支持</b>${e[2].split('，')[0]}。</div><div class="d-limit"><b>仍不能证明</b>${e[2]}</div><button class="primary" onclick="dCloseForge()">收入案卷并继续调查</button>`)};
window.dModule=(name)=>{const info={通史导入:['郑国为何变法','春秋后期社会关系变化，旧有礼制难以涵盖新型争讼，公布刑书由此进入历史议程。'],律典研读:['史料怎么读','重点研读《左传·昭公六年》中子产铸刑书及叔向来书，区分原始史料与教学化虚构。'],案例模拟:['你要解决什么','查明鼎文被改的证据链，并决定公开规则是否也约束官吏。'],人物对话:['不是问答题','不同人物会依据身份、利益和礼法立场回应，你的说法会进入最终判词轨迹。'],物证探索:['四件物证','泥范、拓片、私印、值夜簿各有不同证明对象，必须判断证明力与局限。'],学习档案:['自动存档','系统保存人物会面、物证研判、廷议选择、知识节点和最终结局。']}[name]||['模块说明','该模块将在本卷剧情中逐步解锁。'];modal(`<small>学习模块</small><h1>${info[0]}</h1><p>${info[1]}</p><button onclick="dClose()">返回平台</button>`)};
document.addEventListener('click',e=>{const card=e.target.closest('.d-module-grid article');if(card)window.dModule(card.querySelector('b')?.textContent||'');const side=e.target.closest('.d-side button');if(side&&!side.onclick)window.dModule(side.textContent.trim().replace(/^[⌂◈◉▣◇]\s*/,''))});
/* 第一卷脚本定稿：石生案、铸刑书与解释权 */
places.splice(0,places.length,
 {id:'gate',n:'城南铸坊',x:15,y:62,sub:'察看鼎范并受理申诉'},
 {id:'hall',n:'司寇公廨',x:44,y:25,sub:'研读叔向来书'},
 {id:'forge',n:'司寇案库',x:72,y:59,sub:'完成四证待核'},
 {id:'court',n:'郑国朝堂',x:49,y:78,sub:'质询、审案与落鼎'}
);
evidence.mold=['石生旧案','残卷记载：石生因界沟争执推搡游氏家臣，原定服劳役三月；当庭质问游章后，改判黥面，旁侧仅有“慢上无礼”四字。','处罚发生明显变化、加刑紧随质问且案卷未载具体依据；不能单独证明游章必然出于报复，也不能证明石生完全无责。'];
evidence.rubbing=['刑鼎拓文','拟公布文字列有若干伤害、争界和扰乱秩序的处罚及适用条件，却没有“质问大夫即处黥刑”的明确规定。','刑书试图公开部分罪刑标准，追加黥刑在新刑书中没有直接对应；不能证明新刑书当然追溯旧案，也不能证明未写入的行为绝不受处理。'];
evidence.seal=['医者验伤简','游氏家臣仅手臂擦伤、未伤筋骨；石生受讯后却有明显杖伤。','伤害结果可能被夸大，并提示讯问中可能发生暴力；不能证明石生未曾推搡，也不能直接证明用刑由游章下令。'];
evidence.watch=['市井争讼簿','铸刑书消息传出后，援引文字要求解释和重审的人明显增加，其中既有真实申诉，也有围绕字句的争执。','公开规则提高了平民提出主张的可能，也支持叔向对争讼增加的部分担忧；不能证明争讼增加必然导致混乱或申诉者都在钻空子。'];
dialogues.gate=[
 ['史墨','公元前536年三月，新郑城南。铜料正在炉中熔化，鼎范内已刻好刑书。文字一旦落鼎，便不能像竹简那样随意改动；可世间案件，哪一件能像铜水一样倒进同一个范里？'],
 ['沈衡','第一处调查：鼎范文字中列有罪名和处罚，但部分适用条件十分简略。你怎样记录？',[['详记文字，同时注明公开规则仍需解释。','prologue_text','知识节点：成文法不会自动消除裁量'],['只抄刑名，适用条件无需过问。','prologue_text_shallow','风险：形式公开仍可能不可预期']]],
 ['沈衡','第二处调查：一捆旧案竹简只记裁断结果，没有写适用了什么规则。你怎样理解？',[['旧制结合礼、身份、惯例与临事判断，并非毫无规范。','prologue_cases','知识节点：理解礼刑秩序的历史语境'],['没有公开条文，就说明当时完全没有规则。','prologue_cases_wrong','风险：把“不公开”误作“无法律”']]],
 ['沈衡','第三处调查：铸坊外，平民盼望知道处罚，旧族家臣却担心百姓拿文字质问贵族。你看见了什么？',[['刑书公开也会改变贵族、官吏和平民的权力关系。','prologue_crowd','知识节点：规则知识不再完全由贵族垄断'],['这只是识字问题，与权力无关。','prologue_crowd_wrong','风险：忽略法律公开的政治影响']]],
 ['史墨','你看见的三处其实是同一个难题：文字能让规则变得可知，却不会自动消除裁量；旧制并非毫无规范，却让普通人难以预期；刑书改变的也不只是形式，而是谁可以要求裁断者说明依据。'],
 ['阿荇','民女阿荇，请司寇府重审家兄石生之案！原判服役三月，只因家兄当堂问游章“加刑依据何在”，便被追加黥刑。'],
 ['游氏家臣','平民质问大夫，便是慢上无礼。大夫依礼加刑，有何不可？'],
 ['沈衡','铜水即将入范，你是否受理这份残卷？',[['立即受理，查明原判为何改变、追加黥刑依据何在。','accept_now','路线：要求权力说明依据'],['暂不受理，待刑书正式公布后再议。','wait_code','路线：新法能否处理旧案'],['拒绝受理，维持大夫依身份临事裁断。','refuse_claim','路线：刑书可能成为单向治理工具']]],
 ['石生','我确曾推人，愿服原定之役。我只问：一句质问，为何要在脸上留下一生的刑印？'],
 ['阿荇','若一句话便可加刑，今日鼎上铸的文字，又是给谁看的？']
];
dialogues.hall=[
 ['子产','田界重分、商旅渐盛，郑国争讼日多。旧礼并非全无规则，却难以处理所有新争。我欲铸刑书，使民知所避。'],
 ['晋国使者','叔向来书：民知有辟，则不忌于上，并有争心，以征于书，而侥幸以成之。'],
 ['史墨','叔向担心条文僵化、争讼增加，也担心掌握解释的官吏受贿。这封信不能只用“守旧”二字打发。'],
 ['沈衡','你建议子产如何回应叔向？',[['叔向只是维护贵族利益，不必回答。','dismiss_shuxiang','忽略了礼治批评中的制度忧虑'],['承认公开会增加争讼，同时保存解释记录并设置申诉。','ack_shuxiang','把公开规则与解释责任结合'],['停止铸刑书，恢复临事议制。','stop_casting','保留灵活性，也恢复秘密裁量'],['只公布刑罚名称，不公布适用条件。','names_only','形式公开，关键解释仍在官署']]],
 ['子产','若吾子之言，侨不才，不能及子孙，吾以救世也。我并非不知其弊，只是今日之郑国，已不能只靠旧礼断新争。'],
 ['史墨','无论铸或不铸，都别把今日之事说成现代法治。贵族政治、身份差等和官吏裁量仍在；刑书只是让部分罪刑规则走向公开。']
];
inspect=function(k){const e=evidence[k];modal(`<small>四证待核 · 证据使用</small><h1>${e[0]}</h1><p>${e[1]}</p><div class="d-proof"><b>材料提示</b>${e[2]}</div><h2>你准备怎样使用这件材料？</h2><div class="d-proof-choices"><button onclick="dJudgeEvidence('${k}','decisive')">视为全案决定性依据</button><button onclick="dJudgeEvidence('${k}','bounded')">只在其证明范围内使用</button><button onclick="dJudgeEvidence('${k}','corroborate')">与其他材料相互印证</button><button onclick="dJudgeEvidence('${k}','exclude')">因存在局限而完全排除</button></div><button onclick="dClose()">暂不收入</button>`)};
window.dEvidence=inspect;
window.dJudgeEvidence=(k,mode)=>{const e=evidence[k];if(!S.evidence.includes(k))S.evidence.push(k);S.choices.push(`proof_${k}_${mode}`);learn(4);save();const good=mode==='bounded'||mode==='corroborate';const notes={decisive:'这件材料被夸大了。真实材料也不能自动包办全案事实。',bounded:'判断稳妥：你把材料限制在它能够证明的对象内。',corroborate:'判断稳妥：你准备让不同来源的材料形成证据链。',exclude:'有局限不等于没有证明力；完全排除会失去有价值的信息。'};modal(`<small>研判反馈</small><h1>${good?'证明边界清楚':'需要修正证据观'}</h1><p>${notes[mode]}</p><div class="d-proof"><b>可以支持</b>${e[2].split('；')[0]}。</div><div class="d-limit"><b>仍不能证明</b>${e[2].split('；')[1]||e[2]}</div><button class="primary" onclick="dCloseForge()">收入案卷并继续</button>`)};
courtQs.splice(0,courtQs.length,
 ['游章称“礼有尊卑，慢上便是罪”。你首先怎样质询？',[['即使应惩戒，为何一定是黥刑，案卷为何不载依据？','ask_basis'],['大夫身份尊贵，无须再说明。','accept_rank'],['新刑书没写，所以石生从未有任何责任。','erase_fault']]],
 ['刑书是否也能约束贵族和作出裁断的官吏？',[['公开规则至少应要求偏离者说明理由。','bind_power'],['刑书只约束平民，大夫自有礼法。','noble_exempt'],['只要文字公开，谁来解释并不重要。','text_enough']]],
 ['石生受审在先，刑书公布在后。旧案应当怎样处理？',[['不直接追溯新法，但审查原裁断是否无据加刑、是否越权。','review_overreach'],['直接依据新刑书改判石生完全无罪。','retro_acquit'],['为维护贵族威望，拒绝任何重审。','refuse_review']]],
 ['你怎样综合四件材料形成调查结论？',[['承认石生推搡责任，以旧案、验伤和其他材料互证追加黥刑是否有据。','evidence_chain'],['一件旧案残卷已经足以证明游章所有动机。','single_proof'],['材料都有局限，索性只听游章的身份判断。','reject_evidence']]],
 ['铜水即将入范。请提交刑书实施的最终制度安排。',[['公开主要罪刑，保存适用与解释记录，并允许申诉越权加刑。','appeal_record'],['向百姓公开，但贵族可以不受拘束。','noble_tool'],['因担心争讼，毁去刑鼎。','destroy_ding'],['完全按照文字机械适用，不必另作解释记录。','mechanical_text']]]
);
courtStep=function(){if(S.court>=courtQs.length)return resolve();const q=courtQs[S.court];const prompt=document.getElementById('dCourtPrompt'),opts=document.getElementById('dCourtOptions');if(!prompt||!opts)return;prompt.textContent=`第 ${S.court+1}/${courtQs.length} 轮：${q[0]}`;opts.innerHTML=q[1].map((o,i)=>`<button onclick="dCourtChoose('${o[1]}')"><i>${String.fromCharCode(65+i)}</i>${o[0]}<small>本项将影响石生案与刑书制度结局</small></button>`).join('')};
resolve=function(){const bounded=S.choices.filter(x=>/^proof_.*_(bounded|corroborate)$/.test(x)).length;const absolute=S.choices.filter(x=>/^proof_.*_decisive$/.test(x)).length;let id='mixed';if(S.choices.includes('destroy_ding')||S.choices.includes('stop_casting'))id='noDing';else if(S.choices.includes('noble_tool')||S.choices.includes('noble_exempt')||S.choices.includes('refuse_review'))id='power';else if(S.choices.includes('mechanical_text')||S.choices.includes('names_only')||(absolute>=2&&!S.choices.includes('appeal_record')))id='shadow';else if(S.choices.includes('appeal_record')&&S.choices.includes('review_overreach')&&S.choices.includes('ack_shuxiang')&&bounded>=2)id='light';else if(S.choices.includes('retro_acquit'))id='storm';learn(5);learn(6);S.ending=id;S.phase='done';save();ending()};
const originalCourt=court;
court=function(){originalCourt();const badge=document.querySelector('.d-caseboard header>b');if(badge)badge.textContent=`廷议第 ${Math.min(S.court+1,courtQs.length)}/${courtQs.length} 轮`};
const oldLoadScript=load;load=function(){const x=oldLoadScript();if(x.scriptEdition!=='shisheng-final'){const fresh=base();fresh.student=x.student||'';fresh.scriptEdition='shisheng-final';return fresh}return x};
const oldSaveScript=save;save=function(){S.scriptEdition='shisheng-final';oldSaveScript()};
window.dRestart=()=>{localStorage.removeItem('ding-teach-v3');S=base();S.scriptEdition='shisheng-final';shell();guide()};
talk=function(lines,id){document.getElementById('dChar').className=`d-char p${id==='gate'?2:0}`;main(`<section class="d-scene"><aside><small>${id==='gate'?'新郑城南 · 铸鼎现场':'郑国司寇公廨'}</small><h1>${id==='gate'?'鼎范、旧案与鼎下喊冤':'叔向来书'}</h1><p>${id==='gate'?'依次调查三处现场，再决定是否受理石生旧案。':'在子产、叔向与史墨的不同立场之间，决定如何回应成文法公开后的新问题。'}</p></aside></section>`);Q=lines.slice();nextLine()};
const oldMapScript=map;map=function(){oldMapScript();const intro=document.querySelector('.d-map-title p');if(intro)intro.textContent='先到城南铸坊察看鼎范、旧案与人群，并受理阿荇申诉；再赴司寇公廨研读叔向来书，随后进入案库研判四证，最后到朝堂完成质询、旧案处理与落鼎裁断。'};
const keepControlsClear=new MutationObserver(()=>{const game=document.getElementById('dingGame'),char=document.getElementById('dChar');if(game&&char&&game.querySelector('.d-guide,.d-platform,.d-forge,.d-caseboard,.d-court'))char.classList.add('hidden')});
keepControlsClear.observe(document.body,{childList:true,subtree:true});
const leaveFirstVolume=window.dExit;window.dExit=()=>{if(S.phase==='done'&&S.ending)window.unlockVolume&&window.unlockVolume(0,S.ending,S.choices);leaveFirstVolume()};
})();
